nerves-project/nerves

docs/Targets.md
Not a lot. Just saw it while reading doc.
=> Fix a missing space.

docs/User Interfaces.md
Justin helped me thru this issue on slack so I thought I would try and add the note to the docs for others to see in case they run into the same issue.  Hopefully it will help.
=> Add note about rebar -v >=2.6.1

docs/Targets.md
The title is pretty straight forward.
One thing to note, is that the `Note` part of the example repeats what has been said just above. I'm not sure this is great.
Feedbacks are welcome.
=> Added example for switching targets

docs/Getting Started.md
Tip from @fhunleth in the nerves channel on slack.
=> DOC: Added a tip about avoiding the prompt when burning an SD card

lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex
@mobileoverlord - hopefully, you can fix up anything that I got wrong. I just wanted to get something started once I noticed that we were lacking `mix` docs for these.
=> Start docs for firmware and firmware.burn

docs/FAQ.md
I was stuck on this for a little while as I was trying to get uart console set up.
=> Make note of specifying baud rate for screen command in FAQ

lib/mix/nerves/utils.ex, lib/mix/tasks/firmware.burn.ex
For reasons I don't understand, System.cmd("which",[]) just hangs on Windows
=> Add support for Windows

docs/Systems.md
I've drafted some docs based on a conversation in Slack about how someone might go about adding support for new Target hardware.
@fhunleth and @mobileoverlord: I haven't been through this process myself yet, so I'm hoping for some feedback about some of the missing details when you have a chance.
=> DOC: How to customize Systems and support new Targets

docs/Getting Started.md, docs/Installation.md, docs/User Interfaces.md
Fixes minor spelling errors in docs:
- Getting Started.md
- Installation.md
- User Interfaces.md
=> Minor Spelling Fixes

lib/nerves/package/providers/http.ex, lib/nerves/utils/http_client.ex, lib/nerves/utils/proxy.ex, mix.exs, test/nerves/utils_text.ex
fixes https://github.com/nerves-project/nerves/issues/41
Todo
=> Add progress to artifact downloads

bootstrap/lib/mix/tasks/nerves/local.ex
No checking if Nerves is outdated, but at least an easy way to update the local archive. I 'borrowed' the code from Phoenix.
Solves #61
=> Add `mix local.nerves` to update local nerves archive

bootstrap/lib/mix/tasks/nerves/new.ex, bootstrap/templates/new/mix.exs
sets runtime false on compile time deps and includes nerves_runtime in targets deps
=> Include nerves_runtime

RELEASE.md
Trying to capture the steps for cutting a release of `nerves` and `nerves_bootstrap` to make things more smooth and repeatable as we work on more-frequent releases.
=> Document the Nerves RELEASE procedure

lib/nerves/utils/http_client.ex
An attempt to fix #96
In the [erlang 19.3 release](http://erlang.org/download/otp_src_19.3.readme) there was a change made to include the port number in the host header during a redirect. This breaks the signing that happens for AWS download links. The broken redirect then manifests as an error [downloading artifacts](https://github.com/nerves-project/nerves/issues/96).
A minimal reproducible on the error and a way to verify the fix is the run: `$ mix run -e 'Nerves.Utils.HTTPClient.start_link |> elem(1) |> Nerves.Utils.HTTPClient.get("https://github.com/nerves-project/toolchains/releases/download/v0.10.0/nerves_toolchain_armv6_rpi_linux_gnueabi-0.10.0.darwin-x86_64.tar.xz") |> IO.inspect'`
/cc @mobileoverlord @ghitchens
=> handle redirects manually

docs/Systems.md
Add `:nerves_runtime` dependency to `deps` function as this is now part of the generated mix.exs
=> Update section on customizing mix.exs

bootstrap/templates/new/README.md, test/fixtures/artifact_override/mix.exs, test/fixtures/simple_app/mix.exs, test/fixtures/simple_app_v1/mix.exs
The first change updates old references to NERVES_TARGET. The second change cleans up some descriptions.
=> Mix target updates

lib/nerves/package/providers/docker.ex, template/Dockerfile
fixes https://github.com/nerves-project/nerves/issues/112
=> fix locale issues in docker image

lib/nerves/package/providers/docker.ex, lib/nerves/utils.ex, test/nerves/provider/docker_test.exs
fixes https://github.com/nerves-project/nerves/issues/110
=> generate random alpha num for docker id

bootstrap/lib/mix/tasks/nerves/new.ex
The two commits update the nerves.new help and the nerves.new information after a successful run to be more similar to 'mix new' and add more details.
=> Update nerves.new docs

lib/mix/nerves/utils.ex
=> made fwup version-check more robust by trimming version number

bootstrap/lib/mix/tasks/nerves/new.ex, docs/Systems.md
This also relaxes the version requirement so that minor version changes
are allowed.
=> Bump nerves_runtime version

.gitignore, docs/cheatsheet/Makefile, docs/cheatsheet/README.md, docs/cheatsheet/cheatsheet.tex, docs/cheatsheet/nerves-logo.eps
See `README.md` for notes.
Check out the PDF [here](https://www.dropbox.com/s/y3y8u9s22f8oapw/nerves_cheatsheet.pdf?dl=0) if you don't have time to render it manually.
=> Add cheatsheet to docs folder

CHANGELOG.md, bootstrap/CHANGELOG.md, bootstrap/mix.exs, bootstrap/templates/new/config/config.exs, docs/Advanced Configuration.md, docs/FAQ.md, lib/mix/tasks/firmware.ex, lib/nerves/package.ex, mix.exs
Also changed the recommendation to put the `rootfs_overlay` directory at the project root instead of under `config`.
=> Replace `rootfs_additions` with `rootfs_overlay`

docs/Advanced Configuration.md
* Purge remaining references to FAT application partition
* Re-flow paragraphs to 80 chars
* "File system" -> "filesystem"
* Update examples for split boot partition
=> Update and re-flow the Advanced Configuration docs

lib/nerves/package/providers/docker.ex, lib/nerves/package/providers/local.ex
=> Fix hung nerves.system.shell

bootstrap/templates/new/config/config.exs
=> Move the bootloader config before import_config

lib/nerves/package/providers/docker.ex, lib/nerves/package/providers/docker/image.ex, lib/nerves/package/providers/docker/utils.ex, lib/nerves/package/providers/docker/volume.ex, template/Dockerfile
Bring docker enhancements into 0.7.x
=> V0.7.x docker

docs/Installation.md
Update installation docs to recommend  ASDF for managing Erlang and Elixir versions.
Also, re-flow paragraphs to 80 characters.
=> Update installation docs to recommend  ASDF

docs/Systems.md
For folks like me who like to copy and paste code snippets!  :D
=> Update code snippet for system dependency syntax

docs/Installation.md
This is sooooo much easier to remember!
=> Update nerves_bootstrap instructions to the hex way

docs/Advanced Configuration.md, docs/Getting Started.md, docs/Installation.md, docs/User Interfaces.md
This also aligns the docs with the current Nerves style recommendations.
=> Make use of dollar sign prompts consistent 

docs/Advanced Configuration.md, docs/Getting Started.md, docs/Installation.md, docs/Systems.md, docs/User Interfaces.md
This mostly-reverts #215 based on further discussion about #209 and looking at examples of how others in the community are handling this particular aspect of their documentation.
I also fixed a couple of small formatting issues that I noticed while reviewing for consistent use of prompts.
=> Add prompts to docs per #209

docs/Systems.md
Fixes https://github.com/nerves-project/nerves/issues/207
=> update docs to remove nerves.exs

docs/Installation.md
Also mark completion step as optional
=> Fix typo on installation doc

docs/Installation.md
=> Bump Erlang and Elixir versions in docs

docs/Internals.md
There are quite a few moving pieces in nerves.precompile, and this is a rough pass at documenting them.
Let me know if this should be captured in a different place.
=> Document nerves.precompile Call Tree

CHANGELOG.md, docs/Systems.md
* Updated example code to better reflect the new project generator output.
* Changed information referring to `artifact_url` to `artifact_sites`
* Added information on how to construct an artifact.
=> Update docs for systems

lib/nerves/artifact/providers/docker.ex
Before this change, the error message says to look at build.log.
It's not obvious that build.log is buried under the deps directory, so
to make this easier, the change tails the build.log and gives the full
path.
=> Provide a better error message on Docker failures

CHANGELOG.md, CODE_REVIEW.md, ISSUE_TEMPLATE.md, README.md, mix.exs, mix.lock
@mobileoverlord I know that you have at least one more change for this rc, but this should get you closer to publishing it when the time comes.
=> v1.0.0-rc.1 prep

lib/mix/nerves/utils.ex
During training at ElixirConf EU we have found that Node.js was interfering with calls to `System.cmd "which", ["some_exec"]`. It seems that it shims `which`.
https://github.com/asdf-vm/asdf/issues/284#issuecomment-366010826
Sigh.
This changes the script to use find_executable instead.
=> use find_executable instead of calling out to which / where

.circleci/config.yml, lib/mix/tasks/firmware.ex
Employ CI to help us keep our formatting in line.
=> Bump the Elixir version on CI and validate formatting

lib/nerves/artifact/build_runners/docker.ex
Docker currently runs as the root user when building Nerves systems. This is problematic when it is required to write some files back to bind mounted host directories such as `deps/nerves_system_br`. This causes permissions issues when cleaning dependencies.
This PR configures the container to override the user id and group id to match that of the executing user.
=> Synchronize user:group permissions between docker, host, and volumes

docs/Getting Started.md, docs/Systems.md, docs/Updating Projects.md, mix.lock
This fixes things like:
* spelling errors
* bad links
* markdown lint warnings
I updated the word of a couple things when I made the pass.
=> Various fixes to docs

docs/Internals.md, mix.exs
This file was added by @mobileoverlord a while back, but never included in the Hexdocs. I added some formatting so it looks a bit better in the tree viewer deal on the left side on hexdocs. Fixes #130
=> Update Internals docs.

docs/Systems.md
Also bumped the target file to the current  kernel version for clarity.
=> Fix documentation for saiving the Linux config.

lib/mix/tasks/firmware.burn.ex
Our intern @jsiems has been getting our environment running inside WSL.  As part of this, he figured out a way burn the SD Card using the Windows fwup.exe.
=> mix firmware.burn inside WSL

lib/mix/tasks/firmware.burn.ex
Missed `mix format` commit in the wsl firmware.burn changes
=> mix format

lib/mix/nerves/utils.ex, lib/mix/tasks/compile.nerves_package.ex, lib/mix/tasks/nerves.artifact.ex, lib/mix/tasks/nerves.artifact.get.ex, lib/nerves/artifact.ex, lib/nerves/artifact/build_runners/docker.ex, lib/nerves/artifact/build_runners/local.ex, lib/nerves/package/platform.ex
This fixes some whitespace deltas in upcoming PRs so that they look
nicer.
=> Trim trailing whitespace

docs/Installation.md
=> Update Erlang and Elixir versions

lib/nerves/artifact/build_runners/docker.ex
The docker build runner currently sets the `uid` and `gid` by passing the arg `--user` in calls to `run`. This PR changes this behavior to set them in the environment and let the updated docker image entrypoint create and switch to the user before `exec`
https://github.com/nerves-project/nerves_system_br/pull/207
This fixes https://github.com/nerves-project/nerves_system_br/issues/206
=> Set the user and group in the entrypoint script.

lib/mix/tasks/firmware.burn.ex
This is a fix for linux to pass variables used when provisioning devices on calls to `mix firmware.burn` on linux under `sudo`. For example, `SERIAL_NUMBER=1234 mix firmware.burn` wasn't working because the variables were being stripped.
=> Pass NERVES_* and SERIAL_NUMBER to fwup during firmware.burn

lib/mix/nerves/utils.ex
This provides a better error message for #317.
=> Bump required fwup version to 1.2.5

priv/templates/release.eex
This fixes https://github.com/nerves-project/nerves_init_gadget/issues/22.
=> Fix URL and clarify cookie in distillery config

docs/Systems.md
Fixes a few inconsistencies and details that have changed since this was originally written.
=> Update custom system docs

lib/mix/tasks/firmware.ex
This makes it easier to turn on debug prints from Distillery to debug
firmware creation.
=> Add --verbose option to mix firmware

mix.exs, mix.lock
This only makes it easy to run Dialyzer. I started fixing things and realized that this was a bigger task than I expected. I think that there are legitimate warnings.
=> Add dialyxir

lib/mix/nerves/utils.ex, lib/mix/tasks/firmware.burn.ex
Should we use wslpath instead of the regex?
=> Use the built-in tool wslpath

lib/mix/tasks/firmware.burn.ex
fixes https://github.com/nerves-project/nerves/issues/343
=> Call mix firmware when calling mix firmware.burn

lib/mix/tasks/burn.ex, lib/mix/tasks/compile.nerves_package.ex, lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.image.ex, lib/mix/tasks/nerves.artifact.ex, lib/mix/tasks/nerves.artifact.get.ex, lib/mix/tasks/nerves.info.ex, lib/mix/tasks/nerves.release.init.ex
Similar to https://github.com/elixir-lang/elixir/pull/8371
I also added `@doc false` to a few functions in task modules that perhaps
weren't made to be public.
=> Add `@impl true` to Mix tasks

docs/Systems.md
=> Fix custom system docs to use Elixir 1.8 targets

lib/mix/tasks/firmware.ex
The rel2fw script in nerves_system_br will raise when passing unexpected options. This prevents breaking existing Nerves systems that are using a version of nerves_system_br < 1.7.1
=> Check version of nerves_system_br before passing rootfs_priority option

docs/User Interfaces.md
`phoenix.server` Is not a valid mix task, should be `phx.server`
=> Fix command to run Phoenix server

docs/Customizing Systems.md, mix.exs
This fixes some links as pointed out on slack.
=> Fix link to custom systems on hex.pm

lib/nerves.ex
Whoops! Looks like somebody's got a case of the Monday's
=> Fix inverted logic in checking for empty priv dirs

docs/User Interfaces.md
Just noticed a couple things in the example config!
=> Fix minor typos in User Interfaces.md

docs/Getting Started.md
Simple typo fix in intro sentence.
=> fix typo in getting started docs

lib/mix/tasks/burn.ex
A potential fix to issue #291 . This fix will no longer require sudo permissions if the user has the permissions to write to the file. If the user is not able to access the given file, it will continue to ask for permissions. 
Have tested and verified the functionality locally on a linux computer, with an already existing file owned by my user, an existing file owned by root, and in a direction that my user owns, and a directory owned by root, and in all cases it appears to function correctly.
=> Fixes an issue where sudo is required to burn the firmware

lib/mix/nerves/preflight.ex
While working on #425, I noticed that WSL was requiring that fwup be installed both in WSL and in Windows in order to successfully build and burn a firmware, but it wasn't checking for both in the preflight check, resulting in unhelpful error messages.
The main change in this PR is to check for both `fwup` and `fwup.exe` executables (of the required versions) when running in WSL. I also took the opportunity to pull out the related code into a module so that there's a few less things in the `Utils` junk-drawer.
=> Improve WSL support in preflight checks

lib/nerves/env.ex, test/nerves/env_test.exs
This will set `SOURCE_DATE_EPOCH` to a value from `config :nerves, source_date_epoch: "1234"` or can be overridden if `SOURCE_DATE_EPOCH` is already defined.
=> Allow source_date_epoch to be set from Config

lib/nerves/env.ex, test/nerves/env_test.exs, test/support/test_case.ex
This is being removed in favor of setting `XDG_DATA_HOME`
=> Remove NERVES_DATA_DIR

lib/mix/tasks/firmware.ex, test/nerves/erlinit_test.exs
Fixes https://github.com/nerves-project/nerves/issues/475
=> Always generate erlinit.config

README.md
2020 Metal level sponsorship updates:
* Remove Letote.
* Add Very.
* Move SmartRent from Silver to Gold level.
depends on: https://github.com/nerves-project/nerves-project.github.com/pull/60
=> Update sponsors in the README

CHANGELOG.md, lib/nerves/artifact/resolvers/github_api.ex, mix.exs, test/nerves/artifact/resolver_test.exs
=> Fix Github API key validation

docs/Installation.md
Add details for developers using `yay` on arch base systems (Manjaro)
=> Add Instructions for Arch based systems (Manjaro)

docs/Getting Started.md, docs/Installation.md
Update the docs with some things that I bumped my head against.
=> minor updates to docs

lib/mix/nerves/utils.ex
It could be possible that `fwup` adds more information of detected
drives. If it did, this would break the automatic SD card detection
logic since it assumes 2 fields, path and size. A field that may be
added is the drive name since that makes it easy to tell the difference
between MicroSD card readers and USB thumbdrives, for example.
This also changes the parsed result from a 2-long list to a 2-tuple.
This was mostly stylistic, but it helped me when testing to make sure
that I covered all places that it was used.
=> Support extra fields from fwup --detect

test/fixtures/release_app/mix.exs, test/nerves/mix_test.exs
I'm pretty sure this isn't the right thing to do, but I wanted to see if CI would start passing.
=> Remove failing test

lib/mix/tasks/firmware.patch.ex
=> Fix target/source swap when generating firmware patches

lib/mix/tasks/firmware.ex
closes out https://github.com/nerves-project/nerves/pull/575/files
=> Clean up checks associated with distillery

docs/Advanced Configuration.md, docs/FAQ.md, docs/Getting Started.md
/data should be used instead of /root
Add a link to info about pushing updates remotely to the getting started
guide
Add notes to FAQ:
- Where to store persistent data
- Applying a firmware update manually (command needs tweaking still)
- Pushing firmware updates remotely
=> Various doc improvements

lib/nerves/utils/http_client.ex
See individual commits for details.
I tested this on public and private GitHub repositories.
=> Revert the commit that removed custom redirect handling; implement fix

docs/Systems.md, lib/mix/tasks/nerves.artifact.ex
Hi folks,
* Found a typo in the docs under `Systems.md`.
* Found an unrelated typo while building this PR.
=> Fix very minor typo in documentation.

docs/Compiling Non-BEAM Code.md
See https://github.com/nerves-project/nerves_system_br/commit/71f0830f9eb87bd854247e1d88d10c7faaed3e38
=> Add CPPFLAGS to environment variable list

lib/mix/tasks/firmware.unpack.ex
`mix firmware.unpack` would only look for a firmware that was currently built
for a project. Sometimes you may have multiple firmware files to inspect that
were built elsewhere and this would be a convenient tool to inspect them.
This adds `--fw path/to/.fw` support for those cases. It also changes the default
outpath to be the firmware file name with `.unpacked` appended. (i.e. `hello_nerves.fw -> hello_nerves.unpacked`)
=> Allow specifying firmware path with firmware.unpack

docs/Experimental Features.md
=> Update Experimental Features.md

docs/Using the CLI.md, mix.exs
In addition to just having more documentation, the idea is to replace the RingLogger info in the MOTD with a URL to this page.
=> Add docs for using the CLI

lib/nerves/artifact.ex, lib/nerves/system/br.ex
Remove a few more Dialyzer warnings. Still lots left.
=> Fix Dialyzer warnings

docs/User Interfaces.md
Add Hello Phoenix example to the intro.
=> Update User Interfaces.md

lib/nerves/artifact.ex, lib/nerves/artifact/build_runner.ex, lib/nerves/artifact/build_runners/docker/volume.ex, lib/nerves/artifact/cache.ex, lib/nerves/env.ex, lib/nerves/erlinit.ex, lib/nerves/package.ex, lib/nerves/utils/wsl.ex, test/nerves/artifact_test.exs
- Remove unused function
- Trivial spec improvements
- Fix credo consistency warnings in wsl.ex
- Fix errant specs
=> Various simple spec/dialyzer updates

lib/nerves/artifact.ex, lib/nerves/env.ex
Dialyzer reports these as unreachable and they look like it.
=> Delete unreachable code paths

README.md
Co-authored-by: Frank Hunleth <fhunleth@troodon-software.com>
=> Add Nerves table of contents for repositories

README.md, docs/Installation.md
- Update host requirements
- Update asdf branch version
=> Update host requirements and asdf install

docs/IEx with Nerves.md, mix.exs
I think titling this chapter as IEx will connect more with new users since
that will be somewhat familiar and is the intended target. "CLI" seems
to imply this might be some local binary you run for the device which
isn't quite the case either..
=> Rename `Using the CLI.md` to `IEx with Nerves.md`

docs/Compiling Non-BEAM Code.md
Also add link to video explaination about cross-compilation and Makefiles
=> Format lirbary recommendations in `Compiling Non-Beam Code.md`

README.md
- Add descriptions to toolchains
- Nerves.Bootstrap and Nerves.Runtime have dots
=> Minor fixes to the Nerves repo directory

lib/nerves/artifact.ex, lib/nerves/artifact/build_runners/docker.ex, lib/nerves/artifact/build_runners/docker/volume.ex
- Document side effect of calling Docker.Volume.id/1
- Add specs
=> Document Docker volume side effect and simplify

.circleci/config.yml, .credo.exs, lib/mix/nerves/preflight.ex, lib/mix/nerves/shell.ex, lib/mix/tasks/burn.ex, lib/mix/tasks/compile.nerves_package.ex, lib/mix/tasks/firmware.ex, lib/nerves/artifact.ex, lib/nerves/artifact/build_runners/docker.ex, lib/nerves/artifact/build_runners/docker/image.ex, lib/nerves/artifact/build_runners/docker/utils.ex, lib/nerves/artifact/resolver.ex, lib/nerves/artifact/resolvers/github_api.ex, lib/nerves/env.ex, lib/nerves/package.ex, lib/nerves/package/utils/squashfs.ex, lib/nerves/port.ex, lib/nerves/release.ex, lib/nerves/utils.ex, lib/nerves/utils/file.ex, lib/nerves/utils/http_client.ex, lib/nerves/utils/proxy.ex, lib/nerves/utils/shell.ex, lib/nerves/utils/stream.ex, lib/nerves/utils/wsl.ex, test/support/test_case.ex, test/support/test_server/router.ex
Also does all the minor adjustments needed for Credo (and dialyzer) to pass
`Nerves.Release` file is ignored for now as it is a bigger refactor and is being handled in #757
=> Enable Credo in CI

lib/mix/tasks/firmware.ex
Fixes https://github.com/nerves-project/nerves_system_br/issues/495
Some directories are mounted as filesystems on the device which overwrite any files the overlay may have placed there. To prevent confusion, this will detect these clashes and fail the firmware build with a helpful warning.
=> Check if supplied rootfs_overlays have incompatible directories

docs/Installation.md
Update link URL for Homebrew so it loads the site vs trying to load a file from the repo.
=> Fix Homebrew link in Installation doc

docs/Customizing Systems.md
Make the instructions more consistent and easier to follow by pointing to the specific location in mix.exs that needs to be changed.
Original:
New:
=> Make the custom system doc mix.exs updates easier to follow

docs/Installation.md
A minor improvement in README
Currently the latest version of asdf is `0.11.0`
=> Update asdf version in the installation guide

docs/Installation.md
https://github.com/eddiezane/lunchy/issues/57#issuecomment-448588918
=> Update Installation.md to fix zsh missing `complete` command

test/nerves/port_test.exs
Taken from https://github.com/fhunleth/muontrap/commit/8e16ef3a26ffd776aff06d5a215788db22021c6f
With newer versions of MacOS, executables are more tightly controlled. In the case of this test, copying `/bin/echo` to a new location locks the file from being executed again which fails the test.
This instead creates a symlink file to use during the test (following the test pattern in Elixir core with https://github.com/elixir-lang/elixir/blob/v1.15.0/lib/elixir/test/elixir/system_test.exs#L121)
=> Fix absolute path test on MacOS

lib/mix/tasks/compile.nerves_package.ex
The same error was being used whether nerves_boostrap wasn't started or completely missing. This would lead to confusing error messages for users and unhelpful instructions in the case the archive is totally missing.
This changes that check to use a separate error if `nerves_bootstrap` is completely missing and needs to be installed
=> Adjust compilation error when `nerves_bootstrap` missing

docs/Getting Started.md
There are two main changes in this PR:
1. The Nerves Livebook project has been moved higher up as to highlight the fantastic first-time experience.
2. Some readability suggestions which addresses general reading flow and grammar.
=> Some Getting Started changes for readability

docs/FAQ.md, docs/Getting Started.md, docs/Installation.md, docs/Updating Projects.md
A small docs update which makes it easier to find the real hiding place of the Nerves, and Elixir, community.
=> The Elixir community moved from Slack to Discord

.circleci/config.yml, lib/nerves/package.ex, mix.exs
Have been building a few firmwares with this and seems to be working
=> Support Elixir 1.16

lib/nerves/artifact/build_runners/docker.ex
Building on a mac will result in this failure:
```
docker: Error response from daemon: error while creating mount source path '/host_mnt/private/tmp/com.apple.launchd.lINaqsIhwG/Listeners': mkdir /host_mnt/private/tmp/com.apple.launchd.lINaqsIhwG/Listeners: operation not supported.
```
This is failing because Apple doesn't support passing a unix socket across a hypervisor. This happens when trying to use SSH_AUTH_SOCK to mount the ssh-agent (unix) socket for authentication.
Instead, mount the user's ~/.ssh directory so that ssh has access to the user's private keys during the docker container instance running the build.
=> docker: Don't use ssh-agent, instead mount ~/.ssh

guides/introduction/installation.md
Added specifics on how to swap to using lxqt-openssh-lastpass to the NixOS section.
Also fixed one small typo.
=> Added info on how to use lxqt-openssh-lastpass in shell.nix.

guides/introduction/installation.md
Commit 2bf02b7c3724f64ac4ecdf4e6d3cf8f01d5c4883 moved the location of `Installation.md`. This PR adjusts sources to changes.
=> Update installation guide

CHANGELOG.md
=> Fix CHANGELOG.md, the date of v1.11.2

guides/advanced/building-sytems.md
This pull request adds a step-by-step guide for building and customizing Nerves systems using the [nerves_systems] repository. 
[nerves_systems]: https://github.com/nerves-project/nerves_systems
- Environment setup for macOS, Linux, and Windows users.
- Instructions for cloning, configuring, and building systems.
- Guidance on using custom-built systems in Nerves projects.
- Tips for advanced customization using Buildroot configurations.
- Links to related documentation, such as [Customizing Your Nerves System](https://hexdocs.pm/nerves/customizing-systems.html).
- It fills a gap in the current Nerves documentation by providing detailed instructions for advanced users.
- It empowers developers to experiment with and contribute to custom Nerves systems.
=> Add  step-by-step guide for building nerves systems

guides/core/supported-targets.md
Added RPI5 as a supported target. 
https://github.com/nerves-project/nerves_system_rpi5
=> Added RPI5 entry in supported-targets.md

lib/nerves/package.ex
No code changes except to extract private function.
=> Document code to get nerves options on dependency
