docs/User Interfaces.md
This helps distinguish between umbrella the concept, and umbrella the
app name.
=> Change umbrella application name to nervy

archive/nerves_bootstrap/templates/new/rel/.gitignore
I believe this is why the `.gitignore` file in `rel` is not being tracked.  I had the same problem locally.
As discussed on Slack:
Trying to build the archive locally... getting
`** (File.Error) could not read file /Users/wsmoak/projects/nerves/archive/nerves_bootstrap/templates/new/rel/.gitignore: no such file or directory`
indeed it does not seem to be there: https://github.com/nerves-project/nerves/tree/master/archive/nerves_bootstrap/templates/new/rel (edited)
jschneck [1:35 PM] 
thats strange
jschneck [1:37 PM] 
im trying to figure out why its in my local copy but not being tracked
I forced it
its on master
=> Don't ignore the .gitignore file in rel

docs/User Interfaces.md
User Interface doc has instructions to create a sub-app with the name `fw` but then its referenced as `firmware` elsewhere in the doc, just cleaning this up to make it less confusing
=> Correction to fw / firmware app refs

archive/nerves_bootstrap/lib/mix/tasks/nerves.new.ex
The help docs show that `--app` and `--module` are supported, but if you try to use them you get the following error: 
> ** (Mix) Invalid option: --module
Looking at the [mix.new Task](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/new.ex#L46) as a reference I was able to just add `app: :string, module: :string` to the `@switches` list to resolve this issue.
I tested this locally and it worked great! Cheers!
=> Add app and module to switches 

docs/Installation.md
After helping someone out with installation, I think that we need a tl;dr version of the instructions. I made a pass at it in this PR. The additional text in the original seems like it would be useful somewhere, but it led to some interesting confusion. For example, `gstat` is only required on MacOS. If you don't know what it is and google it, you'll find references to Firebird database. I suspect that most people will be happy with blindly installing `coreutils`.
=> Simplify installation instructions

docs/User Interfaces.md
The documentation for how to crete a UI is somewhat out of date. At the momen sqlite does not work and is not needed also brunch is not needed. Configuration for the ui app in the fw app is missing and also configuration for the OTP application is missing. fw.ex must also have a child worker that sets up networking.
=> ui config in fw project and also OTP-configuration

docs/FAQ.md, mix.exs
I've put together a start to a FAQ page with a few items that come up often in the Slack channel.
=> Add a starter FAQ page to the docs

docs/Getting Started.md
Added a note about specifying the target via environment variable to example at the end of the page.
=> Use NERVES_TARGET when building examples

docs/FAQ.md
The questions are currently a level 1 heading, which is too large given the length of the questions. By changing these to level 3 headings, the visual balance of the page is improved.
By using level 3 headings for the questions, level 2 headings are available for use later to group questions once the FAQ becomes large enough. In addition, these future level 2 section headers will render in the navigation tree.
=> Reduced header level of FAQ questions

lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.image.ex
in your mix config you can have something like:
```elixir
def project do
[app: :my_app,
version: "1.2.3",
target: "rpi3",
archives: [nerves_bootstrap: "~> 0.2.0"],
build_embedded: Mix.env == :prod,
start_permanent: Mix.env == :prod,
build_path:  "../../_build/#{target(Mix.env)}",
deps_path:   "../../deps/#{target(Mix.env)}",
images_path: "../../images", # THIS
config_path: "../../config/config.exs",
lockfile: "../../mix.lock",
aliases:     [],
deps:        deps()
]
end
```
=> make output of images configurable

lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.image.ex
Since we do `Path.expand()` now, `Path.join(File.cwd!, ...)` was causing the paths to be duplicated. so when you did `mix firmware` you would expect the firmware to exist in `/home/user/app/_build/rpi3/app.fw` but it really ends up in `/home/user/app/home/user/app/_build/rpi3/app.fw`
=> fix Path.expand() issue causing paths to be duplicated.

bootstrap/lib/mix/tasks/nerves/new.ex, bootstrap/templates/new/rel/.gitignore
This .gitignore is no longer needed since the release build products
aren't stored there any more. It also removes a minor speed bump when
wanting to commit a rel/config.exs.
=> Remove rel/.gitignore from the skeleton

lib/mix/tasks/compile.nerves_package.ex, lib/nerves/package.ex, lib/nerves/package/providers/http.ex, test/nerves/artifact_test.exs
Whenever we are pulling down tar files, if the connection drops the tar file may be incomplete.  To make this a bit more robust, I added code to catch the return code from the tar command.   If it's not 0, then return an error.  Otherwise keep on trucking.
Also, I created a unit test to test this, it passes in a .fw file instead of a tar ball which obviously should throw an error.   The .fw file is fairly large, so I have it skipping it.   Any feedback is welcome, as I wasn't sure what the best strategy for a test would be.
=> Return error when tar command isn't successful

bootstrap/templates/new/rel/vm.args
The easy thing to do is to add parameters at the end of the file without noticing the `-extra`. Add a comment to save me from accidentally doing this in the future.
=> Add note about where args go in vm.args

bootstrap/lib/mix/tasks/nerves/new.ex, bootstrap/mix.exs, bootstrap/templates/new/README.md, bootstrap/templates/new/lib/app_name.ex, bootstrap/templates/new/lib/app_name/application.ex, bootstrap/templates/new/mix.exs, bootstrap/templates/new/test/app_name_test.exs, bootstrap/templates/new/test/application_name_test.exs
This PR updates the new project generator to create a host first environment. Specifically, it makes the following changes:
* Do not invoke the nerves.loadpaths or nerves.precompile for the host target
* Separate OTP application configurations for targets
* --target is no longer needed for `mix nerves.new`
* `NERVES_TARGET` either needs to be `export`ed or prefixed on commands intended to be run for the target.
* ExUnit tests can be invoked on the host
* IEx sessions can be invoked on the host
* Utilities and other code can be invoked on the host
=> Host Target

bootstrap/lib/mix/tasks/nerves/new.ex
Enhanced new project generator to install deps, release config and print additional information.
The new project generator can be tested by cloning the nerves repository and installing the latest bootstrap.
```sh
$ cd cd nerves/bootstrap
$ mix install
```
The, generate a new project
```
mix nerves.new my_app
* creating my_app/config/config.exs
* creating my_app/lib/my_app.ex
* creating my_app/lib/my_app/application.ex
* creating my_app/test/test_helper.exs
* creating my_app/test/my_app_test.exs
* creating my_app/rel/vm.args
* creating my_app/.gitignore
* creating my_app/mix.exs
* creating my_app/README.md
Fetch and install dependencies? [Yn] y
* running mix deps.get
* running mix nerves.release.init
All set!
$ cd my_app
Next, pick a deployent target.
For example: `rpi3` for Raspberry Pi 3 …
```
=> install deps, release config, and print additional info

docs/FAQ.md
Sorry, I know it's petty. Just been  getting into Nerves. Reading through all the Nerves docs and this was the only typo I noticed. Thanks!
=> Fix typo on FAQ page of docs

lib/nerves/package/providers/docker.ex
When building a custom System with the Docker Provider, files were not being properly overwritten when re-building and unpacking a new Artifact. This change removes any existing files for the artifact before unpacking the one that was just built.
=> Clean up artifact dir before unpacking

lib/nerves/package/providers/docker.ex
Docker has changed their version scheme to use date-based versions with a suffix that looks like a pre-release. For example, the version that was just release is `17.3.0-ce` (`-ce` is for Community Edition, as opposed to
Enterprise Edition).
The version requirement needs to be `~> 17.0` instead of `~> 17.3` because the `-ce` suffix makes it decode as if it were a pre-release of `17.3.0`, so it doesn't count as being newer than that.
Unfortunately, this means that we'll need to update annually to support the new year, unless we just change to `>= 0.0.0` or `>= 17.0.0` at some point.
=> Support the new release of Docker

README.md, docs/Advanced Configuration.md, docs/FAQ.md, docs/Getting Started.md, docs/Installation.md, docs/Systems.md, docs/Targets.md, docs/User Interfaces.md
Prepping documentation for release of `nerves` 0.5.0 and `nerves_bootstrap` 0.3.0.
=> Update docs for Nerves 0.5.0 / Bootstrap 0.3.0 release

docs/Systems.md
I missed this one when re-naming the example system from `rpi2_out` to `custom_rpi3`.
=> Fix inconsistency in Systems documenation

docs/User Interfaces.md
For me it looks like thats the current place where the worker should be declared. fw.ex only contains an empty module, start is handled in fw/application.ex.
=> docs: declare worker in lib/fw/application.ex

README.md
This environment variable is read in
`nerves/lib/mix/tasks/firmware.burn.ex` but not documented anywhere. On
Arch Linux systems, `ssh-askpass` is not located in `/usr/bin` (or even
on the path!). This commit updates the documentation with a note
explaining how to solve this situation.
=> Add comment explaining SUDO_ASKPASS

bootstrap/templates/new/mix.exs
Granted that this is some bikeshedding, but the environment was referred to as the "Mix environment" in the `Installation.md` doc. I could only find the shortened version of "env" in code rather than English docs. To me, this looks better and more consistent.
=> Spell out mix environment

mix.exs, mix.lock
This clears up a ton of warnings when generating the documentation.
=> Bump doc and distillery deps in mix.lock

docs/Systems.md, lib/mix/tasks/firmware.burn.ex, lib/nerves/package.ex, lib/nerves/package/providers/docker.ex, lib/nerves/package/squashfs.ex, lib/nerves/utils/http_client.ex, lib/nerves/utils/proxy.ex, lib/nerves/utils/stream.ex, test/fixtures/package/mix.exs, test/fixtures/package/nerves.exs, test/fixtures/system/mix.exs, test/fixtures/system/nerves.exs, test/fixtures/system_platform/mix.exs, test/fixtures/system_platform/nerves.exs, test/fixtures/system_v1/mix.exs, test/fixtures/system_v1/nerves.exs, test/fixtures/toolchain/mix.exs, test/fixtures/toolchain/nerves.exs, test/fixtures/toolchain_platform/mix.exs, test/fixtures/toolchain_platform/nerves.exs, test/fixtures/toolchain_v1/mix.exs, test/fixtures/toolchain_v1/nerves.exs
I was doing some work w/ `Elixir 1.5.0-dev` and I noticed a whole bunch of deprecation warnings on `Nerves` when I built a nerves project. I figured I'd put a PR to start the process of cleanup in prep for the new release of `Elixir`. I know `Nerves` loves to live at the bleeding edge ;)
- Two changes to the `String` API:
- `String.strip` -> `String.trim`
- `String.to_char_list` -> `String.to_charlist`
=> Update Nerves for Elixir 1.5 deprecations

bootstrap/templates/new/config/config.exs
While this information is in the Nerves instructions, having it here as
well is really convenient and saves having to look it up.
=> Add commented-out instructions for enabling rootfs_additions

bootstrap/lib/mix/tasks/nerves/new.ex
regex sigils precompile is causing issues with the installer producing false positives. Recompiling regex fixes the issue.
Info from elixir
https://hexdocs.pm/elixir/Regex.html#module-precompilation
Solved in Phoenix installer
https://github.com/phoenixframework/phoenix/commit/effdd2b40e194d1017d4a35235cdd99e4ee7a78e
=> recompile regex before executing

bootstrap/templates/new/mix.exs
Splitting lock files by target will eliminate cross target dependency issues.
=> split lock files by target

lib/nerves/package.ex, test/nerves/artifact_test.exs
I ran into this based on a typo. Previously, the message was printed and
processing carried on. If you were lucky, it would crash, but on
something later. This exits `mix` as soon as it's detected and provides
some info on where to look for what's probably a typo.
=> Error out when package version or type are missing

lib/nerves/env.ex
This errors out immediately when the path is wrong rather than let
execution continue to hit some other issue.
=> Error out if NERVES_SYSTEM is set incorrectly

lib/mix/tasks/firmware.ex
I'm looking for feedback on fields and naming as well. Since firmware metadata is going to become a lot easier to access and useful thanks to `Nerves.Runtime.KV`, I attempted to fill in some of it. This only works if you're using the `fw_metadata` branch of `nerves_system_rpi0` and branches of `nerves_runtime`, so don't merge!
Here's an example on the target:
```
iex(10)> Nerves.Runtime.KV.get_all
%{"a.nerves_fw_application_part0_devpath" => "/dev/mmcblk0p3",
"a.nerves_fw_application_part0_fstype" => "ext4",
"a.nerves_fw_application_part0_target" => "/root",
"a.nerves_fw_architecture" => "arm", "a.nerves_fw_author" => "Yours truly",
"a.nerves_fw_description" => "New and improved",
"a.nerves_fw_platform" => "rpi",
"a.nerves_fw_product" => "My Bestest Product",
"a.nerves_fw_version" => …
```
=> Propogate mix.exs configuration to .fw metadata

bootstrap/lib/mix/tasks/nerves/clean.ex, bootstrap/lib/mix/tasks/nerves/env.ex, lib/nerves/env.ex, lib/nerves/package.ex, lib/nerves/package/provider.ex, lib/nerves/package/providers/docker.ex, lib/nerves/package/providers/http.ex, lib/nerves/package/providers/local.ex, lib/nerves/package/providers/path.ex
This will fix a few things with the docker provider. Instead of  adding the checksum to the container name, the same container will be used for the life cycle of the application. It also adds the functionality to clean the artifacts, starting with the docker provider. You can call `mix nerves.clean` and if a container has been made, it will remove it. This process could be hooked into `mix clean` but we might want to play around with it a little before making it happen always on ever clean.
=> Remove checksum from docker container name

CHANGELOG.md, lib/nerves/package/providers/docker.ex, mix.exs, test/nerves/provider/docker_test.exs
Docker has a sem ver version where the minor number contains a leading zero. This is causing `Version.parse/1` to return an `:error` because it does not handle leading zeros.
```
iex(1)> Version.parse("17.0.1")
{:ok, #Version<17.0.1>}
iex(2)> Version.parse("17.03.1")
:error
```
This PR implements a function to strip the leading zeros and compare.
=> strip sem ver major, minor, patch before parsing it

bootstrap/templates/new/rel/vm.args
Here's a sample session of the new behavior:
iex(8)> # Press CTRL+C
iex(9)> ** (EXIT) interrupted
iex(9)> ** (EXIT) interrupted
iex(9)> ** (EXIT) interrupted
iex(9)> :timer.sleep(1232421414)
** (EXIT) interrupted
iex(9)>
User switch command
--> s sh
--> c
Nerves Interactive Command Shell
Type Ctrl+G to exit the shell and return to Erlang job control.
This is not a normal shell, so try not to type Ctrl+C.
/srv/erlang[1]> ls
releases
lib
/srv/erlang[2]> Interrupted
/srv/erlang[2]> Interrupted
=> Pass +Bc in vm.args to avoid accidental CTRL+C

bootstrap/lib/mix/tasks/nerves/precompile.ex, lib/nerves/env.ex
This fixes an issue where nerves.precompile could not be called when the mix project on the top of the stack is the nerves_system_*. This will also safely check for a nerves package config before trying to load it when calling `ensure_loaded/2`
=> Allow the nerves_package compiler to safely be invoked on an individual package

lib/nerves/package/providers/local.ex
This affects only the local provider.  Previously it was removing the system artifact folder on every build, causing the build to start over from scratch every time.
This changes the behavior so that the system artifact folder is only removed when `mix nerves.clean <system>` or `mix nerves.clean --all` is called.
=> Remove system artifact dir only when instructed by mix nerves.clean

bootstrap/templates/new/rel/vm.args
Shell history with OTP 20 is now controlled via a commandline option.
This enables it by default in new projects.
=> Add option to enable shell history to template

docs/Installation.md
I just found out that on a fresh Ubuntu 16.04 server, python is not included. This led to this error:
```
** (FunctionClauseError) no function clause matching in String.replace_suffix/3
(nerves_bootstrap) lib/mix/tasks/nerves/loadpaths.ex:16: Mix.Tasks.Nerves.Loadpaths.run/1
(nerves_bootstrap) lib/mix/tasks/nerves/precompile.ex:25: Mix.Tasks.Nerves.Precompile.run/1
(mix) lib/mix/task.ex:300: Mix.Task.run_task/3
(mix) lib/mix/task.ex:332: Mix.Task.run_alias/3
(mix) lib/mix/task.ex:265: Mix.Task.run/2
(mix) lib/mix/tasks/deps.compile.ex:62: Mix.Tasks.Deps.Compile.compile/2
(mix) lib/mix/tasks/deps.loadpaths.ex:83: Mix.Tasks.Deps.Loadpaths.deps_check/2
(mix) lib/mix/tasks/deps.loadpaths.ex:27: Mix.Tasks.Deps.Loadpaths.run/1
```
The clue was:
```
umask 0022 && make -C …
```
=> Add python to the requirements for building custom systems

docs/User Interfaces.md
I'm not sure if phoenix renamed this parameter at some point (See https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/config/dev.exs#L25), but now it's `code_reloader`. Incorrectly naming the parameter in this example causes Phoenix to crash, since live_reload isn't available on the device.
=> Correct code_reloader parameter

bootstrap/lib/mix/tasks/nerves/loadpaths.ex
My project was borken, erroring on this `raise`. it originally gave me this: 
```
** (FunctionClauseError) no function clause matching in System.put_env/2                       
(nerves_bootstrap) lib/mix/tasks/nerves/loadpaths.ex:16: Mix.Tasks.Nerves.Loadpaths.run/1  
(nerves_bootstrap) lib/mix/tasks/nerves/precompile.ex:25: Mix.Tasks.Nerves.Precompile.run/1
(mix) lib/mix/task.ex:294: Mix.Task.run_task/3                                             
(mix) lib/mix/task.ex:326: Mix.Task.run_alias/3                                            
(mix) lib/mix/task.ex:259: Mix.Task.run/2  
(mix) lib/mix/tasks/deps.compile.ex:62: Mix.Tasks.Deps.Compile.compile/2                   
(mix) lib/mix/tasks/deps.loadpaths.ex:83: Mix.Tasks.Deps.Loadpaths.deps_check/2            
(mix) …
```
=> Add more helpful error message to loadpaths task.

bootstrap/templates/new/mix.exs, bootstrap/test/nerves_new_test.exs
System apps should be appended as a list so there is a clear place for putting deps that are only for a certain system. For example, I have a project with qemu and rpi0 and only rpi0 also needs nerves_init_gadget.
```elixir
def deps("host"), do: []
def deps(target) do
[
{:bootloader, "~> 0.1"},
{:nerves_runtime, "~> 0.4"},
] ++ system(target)
end
#def system("qemu_arm"), do: {:nerves_system_qemu_arm, ">= 0.0.0", runtime: false}
def system("qemu_arm"), do: [{:nerves_system_qemu_arm, path: "../../nerves_system_qemu_arm"}]
def system("rpi0") do
[
{:nerves_system_rpi0, "~> 0.17.0"},
{:nerves_init_gadget, github: "fhunleth/nerves_init_gadget"}
]
end
def system(target), do: Mix.raise "Unknown MIX_TARGET: #{target}"
```
=> append system deps as a list

lib/mix/nerves/utils.ex
This patch allows for the latest version of [fwup](https://github.com/fhunleth/fwup) which is `1.0.0-dev` to work with nerves.
=> handle fwup dev versions as well

lib/nerves/env.ex, lib/nerves/package.ex
The config can be read in form the mix file and packages can be identified with backwards compatibility (until after 1.0).
TL;DR
Turns this:
```elixir
use Mix.Config
version =
Path.join(__DIR__, "VERSION")
|> File.read!
|> String.trim
pkg = :nerves_system_rpi0
config pkg, :nerves_env,
type: :system,
version: version,
compiler: :nerves_package,
artifact_url: [
"https://github.com/nerves-project/#{pkg}/releases/download/v#{version}/#{pkg}-v#{version}.tar.gz",
],
platform: Nerves.System.BR,
platform_config: [
defconfig: "nerves_defconfig"
],
checksum: [
"nerves_defconfig",
"rootfs_overlay",
"linux-4.4.defconfig",
"fwup.conf",
"cmdline.txt",
"config.txt",
"post-createfs.sh",
"VERSION"
]
```
Into this:
```elixir
defmodule NervesSystemRpi0.Mixfile do
use Mix.Project
@app :nerves_system_rpi0 …
```
=> Move Nerves config from nerves.exs to mix.exs

README.md
The relative link doesn't seem to expand correctly.
=> Fix link to contributors graph in README

lib/mix/nerves/utils.ex
This pulls in the `meta-misc` and `meta-vcs-identifier` support that is
being used for the Nerves system regression tests. This is starting to
cause errors for people who haven't updated `fwup` in a while, so just
catch it here. Plus `fwup` is getting close to 1.0, so catching everyone
up will be useful in exposing any issues in the latest builds.
=> Bump fwup requirement to v0.15.x

lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.image.ex, lib/mix/tasks/nerves.release.init.ex
Most of the Nerves mix tasks didn't appear in `mix help`. This fixes that.
=> Add shortdocs and minor help text updates

lib/mix/tasks/firmware.image.ex
The default is the OTP application name dot img.
=> Remove need for specifying a .img name

lib/nerves/env.ex, lib/nerves/package/providers/http.ex
The cache dir is set by defining `NERVES_DL_DIR` env var or it will default to  `~/.nerves/dl` if undefined. Before the http provider attempts to fetch an artifact, it will check in the download dir for one. If it does end up downloading an artifact, it will be downloaded to the download_dir location and unpacked in the artifact_dir as to follow the current workflow. Does not break backwards compatibility.
=> check the download_dir location for a tar before downloading one

CHANGELOG.md, lib/nerves/package/providers/http.ex, mix.exs
Ensure that the dl dir exists before trying to write to it.
Release 0.7.4
=> ensure dl dir exists before trying to write to it

docs/User Interfaces.md
Initially I was just going to update the docs for umbrella project layout w/ phoenix 1.3 and nerves_network, but then found #196 and learned of the poncho projects. So instead of wholly removing the umbrella project configuration, I've attempted to separate the project organization from the configuration of networking and phoenix. I've followed these steps in both project configurations with success.
* phoenix -> 1.3
* nerves_networking 0.6.0 -> nerves_network 0.3
* poncho projects recommendation
=> Update docs for Phoenix UI

bootstrap/templates/new/config/config.exs
If you have two firmware projects in the same umbrella, as they share much of the same code, then by default bootloader will only work for one of them. This is due to the way umbrellas are configured to load the configs from apps in the umbrella.
It's a bit of an edge case, but I think it's a reasonable way to structure a project for co-operating but different devices.
This fix ensure that the bootloader is configured from the project in which you're running `mix firmware`.
=> Configure bootloader with the app name derived from Mix.Project.config

bootstrap/templates/new/rel/vm.args
Previously, colors were disabled by default, but it seems like most
people will have terminals that support the ANSI escape sequences and
they look nicer.
=> Enable colors in IEx by default

docs/Targets.md
This removes Linkit, Galileo, AG150, and Alix. It adds the generic
x86_64 target.
=> Update official target list

lib/nerves/utils/http_client.ex
CI Logs are being filled with progress bars instead of helpful log messages. We need to suppress them. This might not be the best name, but its based off CTNG's variables.
=> progress bar can be disabled

lib/nerves/package.ex, lib/nerves/package/providers/local.ex, lib/nerves/utils/stream.ex
When a local build would encounter an error while trying to produce an artifact the command would return with a normal exit status and appear like nothing went wrong. This makes changes to not only raise but to show some of the tail of the build log.
=> raise when artifact build encounters an error

lib/mix/tasks/firmware.ex, lib/nerves.ex, priv/templates/release.eex
This will simplify the release config and move the settings for Nerves into a plugin.
Instead of this
```elixir
release :example_proj do
set version: current_version(:example_proj)
plugin Bootloader.Plugin
if System.get_env("NERVES_SYSTEM") do
set dev_mode: false
set include_src: false
set include_erts: System.get_env("ERL_LIB_DIR")
set include_system_libs: System.get_env("ERL_SYSTEM_LIB_DIR")
set vm_args: "rel/vm.args"
end
end
```
we use this
```elixir
release :example_proj do
set version: current_version(:example_proj)
plugin Bootloader
plugin Nerves
end
```
This PR also adds a commit to skip the archival release phase.
Depends on:
https://github.com/nerves-project/bootloader/pull/6
=> Nerves release plugin

docs/Systems.md, lib/nerves/package.ex, lib/nerves/package/artifact.ex, test/nerves/artifact_test.exs
This was only needed to support finding artifacts from the `nerves_system` and `nerves_toolchain` compilers which have long been deprecated.
=> remove legacy compiler key from package struct

lib/mix/nerves/utils.ex, lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.image.ex
This is the first step in drying up this code so that we can add a more
helpful message when the user simply forgot to set the `MIX_TARGET`
before running mix.firmware and related Mix tasks.
Background:
Thanks!
=> Unify checks for NERVES_SYSTEM & NERVES_TOOLCHAIN

docs/Systems.md, lib/nerves/package.ex
This was out-of-sync after removing the `nerves.exs` docs in #221. Rather than updating this file as well, I just referred to those docs so we don't have to maintain it in two places.
This should finish up #207.
=> Refer to Systems.md from Nerves.Package module docs

CHANGELOG.md, lib/nerves.ex, mix.exs
`Path.join` doesn't work for atoms, and `Mix.env` is an atom, like `:dev` or `:test`.
It was causing `mix firmware` to fail with an error like:
```
Plugin failed: no function clause matching in IO.chardata_to_string/1
```
By shimming an `Exception.format_stacktrace(System.stacktrace)` into Distillery, I was able to get the following clue as to what the problem was:
```
before_assembly
(elixir) lib/io.ex:445: IO.chardata_to_string(:dev)
(elixir) lib/path.ex:500: Path.do_join/3
(elixir) lib/path.ex:495: Path.join/2
(elixir) lib/path.ex:472: Path.join/1
lib/nerves.ex:10: Nerves.before_assembly/2
(distillery) lib/mix/lib/releases/plugins/plugin.ex:174: Mix.Releases.Plugin.call/3
(distillery) lib/mix/lib/releases/assembler.ex:30: Mix.Releases.Assembler.assemble/1
(distillery) …
```
=> Stringify the Mix.env before passing it to Path.join

lib/mix/nerves/utils.ex
This is a followup to #219. It provides a better error message when `NERVES_SYSTEM` or `NERVES_TOOLCHAIN` are missing when running `mix firmware` and related tasks. It is particularly useful if you are opening multiple terminal tabs and/or use Tmux since the environment variables are not shared between terminal sessions.
Before:
After:
Any/all feedback is welcome.
Thanks!
=> Better error when NERVES_SYSTEM or NERVES_TOOLCHAIN are missing

CHANGELOG.md, lib/nerves.ex, mix.exs
@mobileoverlord and I are still not sure why this was added originally, but it seems to not be needed and it causes problems when you run `mix firmware` without first running `mix compile`.
=> Don't override the output_dir in the Distillery Plugin.

CODE_REVIEW.md, README.md, docs/CONTRIBUTING.md
This PR depends on the CODE_OF_CONDUCT one, since it references that in the document.
I put both this and `CODE_OF_CONDUCT.md` in the `docs` directory so that they show up both in the Hexdocs documentation and get recognized by GitHub when opening a PR/Issue/etc.
This is still work-in-progress:
=> Contributing Documentation

docs/Installation.md
It's not obvious anymore where to get the .ez file. To support users
with old versions of nerves_bootstrap, we still have it posted on the
archives Github, but that will hopefully go away and we don't link to it
anyway. If users get an error from the hex install, I'd think that it
would be something that wouldn't be resolved by a manual download.
=> Remove archive installation failure instructions

lib/nerves/utils/http_client.ex
If the Content-Disposition header is missing when downloading an artifact, infer the filename from the URL instead of blowing up. This adresses #143.
I'm not sure if using Path.basename/1 with an URL is too neanderthal, but it works.
=> Nerves.Util.HTTPClient: Don't blow up on missing Content-Disposition.

lib/nerves/artifact.ex, lib/nerves/artifact/cache.ex, lib/nerves/env.ex
* Always remove the cache destination when putting an artifact
Fixes: https://github.com/nerves-project/nerves/issues/245
* Fix logic for default providers to only use docker for system types
* Removed some legacy pre 0.4.0 code from `Nerves.Env`
=> Package fixes and updates

lib/nerves/artifact.ex, test/nerves/artifact_test.exs
Instead of using the full checksum for the artifact download file name we will use only the first 7 similar to that of the git default. Since the artifact name also contains the version number, uniqueness isn't going to be an issue.
=> Change artifact download to use short checksums

lib/mix/nerves/shell.ex
The full path is so long that the prompt wraps around and on top of
itself on Linux. This change shortens the path to just the current
directory.
=> Change shell prompt to current directory

docs/Advanced Configuration.md, docs/CONTRIBUTING.md, docs/FAQ.md, docs/Getting Started.md, docs/Installation.md, docs/Systems.md, docs/Targets.md, docs/User Interfaces.md
This contains a few Linux installation fixes based on findings from a
new Ubuntu install. It also adds some packages to make the asdf
installation of Erlang go more smoothly since we push asdf so
frequently.
Not all Markdown warnings were fixed, but a lot. The big change was the
removal of bash prompts which we had decided to do a long time ago, but
never got around to doing.
=> Linux installation updates; markdown warning fixes

lib/nerves/artifact/providers/docker.ex
Currently, docker's edge channel is running version `18.03.00`, which I have installed locally. I was trying to be run `mix firmware` to build my company's firmware and was not able to. I was getting an error message telling me that I did not have docker installed locally, but I knew that was false and verified. After searching the repo I found: https://github.com/nerves-project/nerves/pull/85. Which suggests the possibility of just setting the version to `>= 0.0.0` or `>= 17.0.0`. So I updated the version to string to include `>= 17.0.0`. I am sure if we want more constraints on the versions that are allowed for docker or not, but I wanted to get the conversation started.
While most people are not on the edge channel, I would suspect that a version 18 release will happen at some point …
=> Allow for future docker versions to work with mix firmware

README.md
When I clicked on the link for the contributing guide in the readme I was taken to a 404 GitHub page. This fix should navigate people to the contributing guide correctly from the readme.
=> fix broken contribute guide link

lib/nerves/artifact/providers/docker.ex, mix.lock
This will configure `ssh-agent` forwarding for docker containers to allow assets to be downloaded from ssh connections.
Note: `openssh-client` was not included in the `nerves-project/nerves_system_br` docker image but has recently been added. You will need to update the image before running any new containers.
```
docker pull nervesproject/nerves_system_br
```
Fixes: https://github.com/nerves-project/nerves/issues/260
=> enable ssh-agent forwarding for docker containers

lib/mix/tasks/compile.nerves_package.ex
It is useful to be able to execute mix tasks like `docs` and `hex.*` without invoking the nerves_package compiler. This will fix the issue with disabling the env which caused the nerves_package compiler to fail. 
Example:
`NERVES_ENV_DISABLED=1 mix docs`
=> disable the nerves_package compiler if nerves_env is disabled.

mix.exs
This is so that https://github.com/wojtekmach/changelog can pick it up out of the box (otherwise one needs to do: `changelog github:nerves-project/nerves`)
=> Include CHANGELOG.md in Hex package

lib/mix/tasks/firmware.ex
This allows for a user to supply a list of additions _or_ a single string.
=> Allow for multiple rootfs additions.

lib/mix/tasks/nerves.artifact.get.ex, test/nerves/cache_test.exs
The behavior for downloading artifacts neglected to consult the download directory  before trying to download from artifact sites. This adds a test and fixed the regression.
=> Fix regression with checking downloads directory for artifacts

docs/Systems.md
We've had a few people (myself included) recently confused by this documentation.
I've tried to make the documentation as good as it can be, given how the process actually works.
@fhunleth I'm not much of a Makefile wizard, but do you see an easy way to make these steps "just work" more transparently, so people don't need to manually save a defconfig and copy the result to the right place? It seems like with all of the official systems, the paths will be consistent, so it would only be "unsafe" if they're doing something unusual in a custom system. Even in that case, they'd likely have source control in place that could allow them to put the file where they actually intended and un-do the damage to any accidentally trampled files.
=> Clarify linux and busybox configuration in Nerves System Shell

docs/CONTRIBUTING.md
The dedicated section was removed a while ago and the existing link
turned out to be broken.
=> Update forum link to point to tag

ISSUE_TEMPLATE.md, docs/CONTRIBUTING.md
I noticed while reviewing #280 that the paragraph says that we _will_ use prompts and the examples and actual documentation _don't_ use prompts. I hope this is the last time we switch back and forth. 😿
=> Fix style guide inconsistency

docs/Systems.md
This PR updates the documentation to match the compilers section of the example mix.exs file
=> Minor doc tweak

docs/Installation.md
Corrected library name for install on debian/ubuntu systems .
https://packages.debian.org/stretch/libwxgtk3.0-dev
=> fixed library name in install doc

lib/mix/tasks/nerves.artifact.get.ex, test/nerves/cache_test.exs
When calling `mix deps.get` do not attempt to fetch the artifacts if the artifact path is being overridden by setting its env variable such as `NERVES_SYSTEM`
=> Do not fetch artifacts on deps.get that are set in the env

docs/Systems.md, lib/nerves/artifact/build_runners/docker.ex, lib/nerves/artifact/build_runners/local.ex, lib/nerves/system/br.ex
This PR allows `build_runner_opts` to be used to pass additional arguments to the call to make.
For example:
The `kiosk_system_*`  Nerves packages build QtWebEngine which consume a lot of memory and cause the build to fail in an obscure way. To address the problem we need to reduce the number of `PARALLEL_JOBS` to 8.
Here is how we would pass the args through the mix.exs file
```
defp nerves_package do
[
build_runner_opts: [make_args: ["PARALLEL_JOBS=8"]],
]
end
```
=> Add build runner option for passing args to make

docs/Installation.md
I noticed while getting my new OSX machine set up that `mix deps.get` was failing to download toolchains until I had `xz` installed.
```
Resolving Nerves artifacts...
Resolving nerves_system_rpi0
=> Trying https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.2.2-dev/nerves_system_rpi0-portable-1.2.2-dev-DCDDC11.tar.gz
=> Trying https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.2.2-dev/nerves_system_rpi0-portable-1.2.2-dev-DCDDC11D4EB73C5545F16E6B56B23835950B8F66E6A044B77B0231318E2C365B.tar.gz
=> no_result
Resolving nerves_toolchain_armv6_rpi_linux_gnueabi
** (ErlangError) Erlang error: :enoent
(elixir) lib/system.ex:622: System.cmd("xz", ["-t", "/Users/gmefford/.nerves/dl/nerves_toolchain_armv6_rpi_linux_gnueabi-darwin_x86_64-1.0.0-D5EC22E.tar.x …
```
=> Add xz as a host package requirement in OSX

mix.exs, mix.lock
ex_doc 0.19 doesn't work with Elixir versions < 1.7, so prevent the
dependency from being bumped to avoid errors with Elixir 1.6.
=> Lock ex_doc dep to not go past 0.18.x

lib/mix/nerves/utils.ex, lib/mix/tasks/firmware.burn.ex, lib/mix/tasks/firmware.ex
This makes it possible to have projects or dependencies of projects support configuring the provisioning.conf location. This can be set using the firmware config settings in mix config
```
config :nerves, :firmware,
provisioning: "config/provisioning.conf"
config :nerves, :firmware,
provisioning: :nerves_hub
```
=> Set provisioning information during mix firmware and firmware burn

CHANGELOG.md, docs/Updating Projects.md, lib/mix/tasks/firmware.ex, lib/nerves.ex, lib/nerves/artifact.ex, lib/nerves/env.ex, lib/nerves/package.ex, mix.exs, mix.lock, priv/templates/release.eex
Adds support for distillery 2.x. This requires slight modifications to the Mix project.
Depends on https://github.com/nerves-project/shoehorn/pull/12
=> Add support for Elixir ~> 1.7

docs/Updating Projects.md
It looks like Github changed their way of generating link names.
=> Fix upgrade toc links

docs/Installation.md
Taking out the warning about Elixir 1.7 support and bumping versions to latest available in asdf.
=> Bump Elixir/OTP versions mentioned in install docs

lib/mix/tasks/firmware.burn.ex
Following #324, I’ve made a tiny patch that enables to use `mix firmware.burn` in a Nix shell where `fwup` is available while not installed system-wide. It uses `which` to find its path before calling `sudo`.
=> Make firmware.burn work with fwup from a Nix shell

mix.exs
This will hopefully catch people who still have 1.7.2 installed and
prevent them from hitting the runtime: false issue. Elixir 1.6 is still
supported.
=> If using Elixir 1.7 then require 1.7.3

lib/nerves/utils/file.ex
@michaelkschmidt - I amended your PR (#332). Does this look ok?
Here's the error message now:
```
Resolving Nerves artifacts...
Resolving nerves_system_rpi0
=> Trying /Users/fhunleth/.nerves/dl/nerves_system_rpi0-portable-1.4.0-5F0786C.tar.gz
** (RuntimeError) Could not find 'tar'. See https://hexdocs.pm/nerves/installation.html for required packages.
lib/nerves/utils/file.ex:38: Nerves.Utils.File.cmd/2
lib/nerves/utils/file.ex:5: Nerves.Utils.File.untar/2
lib/nerves/artifact/cache.ex:24: Nerves.Artifact.Cache.put/2
lib/mix/tasks/nerves.artifact.get.ex:88: Mix.Tasks.Nerves.Artifact.Get.put_cache/2
(elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
(elixir) lib/enum.ex:765: Enum.each/2
(mix) lib/mix/task.ex:316: Mix.Task.run_task/3
(nerves_bootstrap) …
```
=> Improve error message reporting when missing tar

lib/nerves/artifact/build_runners/local.ex
Currently the start command is BASH specific, so trying to use any
other shell will cause the shell to be clobbered and unreadable.
For what it's worth, `sh` should also work but I think it's safe to
assume most systems should have `bash` available.
Fixes #320
=> Only allow BASH shell in mix nerves.system.shell

lib/nerves/env.ex
The purpose of this function is to allow for introspection of the mix environment under different targets. This is useful for situations where host tools need access to information from the `host` target as well as a desired target. In order to do this, the vm needs to be restarted which in the case of mix tasks means that the same code paths will be called. Wrapping this call in an environment variable prevents infinite recursion, but limits the caller to only change targets once. This PR makes it the responsibility of the caller to track the state so this function can be called more than once.
=> Make the caller responsible for tracking MIX_TARGET changes

lib/mix/tasks/burn.ex, lib/mix/tasks/firmware.burn.ex
Also moving original firmware.burn task into a new burn task, which only
burns firmware to an SDCard in case folks want to continue working that
way. This is being done in an effort to avoid confusion for new nerves
users as we've noticed that some users misinterpret this task and think
that it does both.  Hopefully this change will make the tasks more
intuitive based on their task names.
Was initially intended to resolve #343 but submitting as an alternative approach which retains the functionality of the old task in case its still desired by some users.
=> Call mix firmware from firmware.burn task.

lib/nerves/utils/http_client.ex
Github Enterprise seems to need `autoredirect: true` to download
large-ish packages
=> Allow http_opts to be overwritten

docs/User Interfaces.md
👋 
Was working on some UI on a nerves side project last week, and noticed that I since I have upgraded to Phoenix 1.4 locally some of the docs were a little out of date.
Not sure if you want to add comments to the effect of, "If you are using Phoenix < 1.4 use `no-bunch`, otherwise `no-webpack`." However, I just assume the user will be using Phoenix 1.4 in my updates, but I can change that if you want.
Also configuring the JSON library is now needed for Phoenix apps. I used `Jason` in the example because Phoenix 1.4 had that installed already and fixed my issue. The issue is [Phoenix defaults to Poison](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix.ex#L71), which if that is not in the deps of the fw directory then warning/errors happen on `mix firmware`. I did not …
=> Update user interface docs for phoenix 1.4

docs/FAQ.md
Really simple change. I just noticed that the FAQ doc in `Using a USB Serial Console` section references example rpi3 setting to use `ttyS0` while the linked hardware description README and default `erlinit.config` both state to use `ttyAMA0`
I'm assuming it needs to be the later one, so here you go.
=> update FAQ.md doc to reference correct rpi3 tty for USB serial console

mix.exs, mix.lock
Cleans up compiler warnings.
Tested on rpi0
=> Bump distillery to 2.0.12

priv/templates/release.eex
This will enable the setting which will work once this PR lands https://github.com/bitwalker/distillery/pull/591
Stripping the release saves some significant space.
On `rpi0`, the size of firmware for a trivial app went from `29.91 Mb` to `21.12 Mb`
=> Default strip_release: true in release config

docs/Targets.md
Not sure what changed, but the URL was getting escaped oddly and it
broke. This seems to make it work.
=> Fix search URL

lib/nerves/env.ex
This seems to happen if you run `mix deps.update --all` and then `mix
firmware`. The artifact doesn't seem to be downloaded. Running `mix
deps.get` fixes the problem.
=> Add help if an artifact directory is missing

.circleci/config.yml, docs/Installation.md
Elixir 1.8.0 has a bug that causes errors with optional dependencies.
The error message involves an optional dependency on the `jason` package
and isn't easy to understand. Specify 1.8.1 here in the installation to
fix the issue for people installing for the first time.
=> Specify Elixir 1.8.1

docs/Systems.md
The Elixir 1.8 docs were accidentally applied to the incorrect file in the docs.
=> Update Custom System docs

lib/mix/tasks/firmware.ex, lib/nerves.ex
The rootfs.priotities file is ordered by highest priority to lowest priority. Each line has two components, file path and a priority number. The priority numbers begin at 32000 and count down to 1000. The files in this list are ordered, beam files followed by app files followed by priv directories. The files are listed in the order erlang will load them.
=> Generate rootfs.priorities file with load order

docs/Systems.md
The markdown for the code block on `build_runner_opts` wasn't correct, which resulted in a nasty headline when reading the docs.
=> Fixes code block for `build_runner_opts`

lib/mix/nerves/shell.ex
This PR addresses two issues.
1. Starting with OTP 21.3.0, requesting the geometry of the window through `:erlang.port_control/3` results in an argument error:
```
** (ArgumentError) argument error
:erlang.port_control(#Port<0.14>, 100, [])
lib/mix/nerves/shell.ex:75: Mix.Nerves.Shell.get_tty_geometry/1
lib/mix/nerves/shell.ex:31: Mix.Nerves.Shell.open/2
(mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
~This will comment this out until the issue is fixed.~
This fixes the issue by first trying the original control number and then attempting the number for OTP >= 21.3.0. Thanks @fhunleth ❤️ 
2. Starting with asdf >= 0.7.0, the `PATH` contained `::`. I was unable to identify where in the code this was happening. This PR sanitizes `::` for the system shell.
Resolves …
=> System shell updates

lib/nerves/artifact/cache.ex
Tar was failing due to a missing destination directory on my laptop.
This makes it fail sooner.
=> Fail immediately on mkdir error

lib/mix/nerves/shell.ex, lib/mix/nerves/utils.ex
Sanitizing the path for `mix nerves.system.shell` fixed the issue with `asdf` >= 0.7.0 but didn't cover other times where a shell is opened. This PR covers the local build runner in the same fashion. 
Fixes https://github.com/nerves-project/nerves/issues/389
=> Sanitize path when opening any shell

lib/nerves.ex
Empty directories are pruned by the release script when constructing firmware. If the sort list contains a priv dir that had no files in it during compile time, the directory will not exist on the target and will throw a warning. An example of this can be seen with the package `mint`. The following warning will appear in the output of the call to `mix firmware`
```
Cannot stat sortlist entry "srv/erlang/lib/mint-0.2.1/priv"
This is probably because you're using the wrong file
path relative to the source directories.  Ignoring
```
This PR excludes empty directories from being included in the sort list.
=> Do not include empty priv directories in sort list

docs/User Interfaces.md
* Changed the names of the top-level and sub-projects to be more clear what they are:
- `my_app` instead of `nervy`
- `my_app_ui` instead of just `ui`
- `my_app_firmware` instead of just `fw`
* Updated to describe the default network setup using `nerves_init_gadget`.
* Use more inclusive language ("we" and "our" instead of "you" and your").
Resolves #406
=> Rework User Interfaces docs

mix.exs
`nerves` and `shoehorn` both depend on `distillery`.`nerves`  locked distillery to 2.0.12 to work around a critical bug in previous 2.0.x versions. `shoehorn` specified its requirement as ~> 2.0 since it was not affected by the same issues. The difference between these two requirement specifications has started to cause the `nerves` dependency to downgrade itself.
=> distillery: update requirement to ~> 2.0.12

docs/Updating Projects.md
Without this you will run into an error compiling shoehorn that looks like:
```
==> shoehorn
Compiling 7 files (.ex)
== Compilation error in file lib/shoehorn/plugin.ex ==
** (CompileError) lib/shoehorn/plugin.ex:2: module Mix.Releases.Plugin is not loaded and could not be found
(elixir) expanding macro: Kernel.use/1
lib/shoehorn/plugin.ex:2: Shoehorn.Plugin (module)
could not compile dependency :shoehorn, "mix compile" failed. You can recompile this dependency with "mix deps.compile shoehorn", update it with "mix deps.update shoehorn" or clean it with "mix deps.clean shoehorn"
```
=> Update upgrade doc to mention shoehorn for Elixir 1.9

docs/Updating Projects.md
Add additional information to the 1.4 -> 1.5 update guide. The `rel/config.exs` file needs to have references to `Mix.Releases.Config` updated to `Distillery.Releases.Config`
=> Update 1.5 guide for distillery config

docs/Installation.md
1)correct elixir version: 1.9.0-otp-22
2)alter .bash_profile to .bashrc to fit wider range of OS
Ubuntu ignores ".bash_profile". ".bashrc" is OK.
(refer to asdf-vm installation procedure)
=> correct installation procedure

lib/mix/tasks/firmware.ex
There is no linkage that we know of between the kernel compiler version, and the OTP version number. Removing this prevents the text from providing recommendations to install versions of OTP that do not exist.
=> Update compiler check recommendation.

lib/mix/nerves/utils.ex
This refactors the error message to one place and gives a hint on the
package to install. E.g., installing coreutils for gstat is the most
helpful if you choose not to read the Nerves install docs (which are
still listed first in the error message).
=> Improve error message when missing packages

docs/Systems.md, lib/nerves/artifact.ex
`System.md` and `lib/nerves/artifact.ex` reference using `:github_releases` with an access_token query param. However, that does not seem to be supported anymore in github.
So this removes that and updates the docs a bit.
As a bonus, I've also tested using `:github_api` for artifacts in a private repo and works like a charm 👌 :tada:
=> Cleanup System.md doc

lib/nerves/utils/wsl.ex, test/nerves/utils_wsl_test.exs
This PR will also enable `mix firmware.burn` for 1903 users 😊
**Reproduction:** Run `mix firmware.burn` inside WSL on Windows 10 Version 1903.
```
$ mix firmware.burn
** (Mix) Could not auto detect your SD card
```
**Reason:** With the introduction of 9P server, each distro's files can be accessed from `\\wsl$\{distro name}\` path.
```sh
$ wslpath -w -a .     
\\wsl$\Ubuntu-18.04\home\nab\hello_nerves\  
```
Cf. https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-windows-10-version-1903/
=> Add 9P path \\wsl$ for mix firmware.burn inside WSL on Windows 10 Version 1903

lib/mix/nerves/utils.ex
Broken out from #455 
The actual section of the page that this link was pointing to no longer exists.
=> Fix broken installation link

lib/mix/nerves/utils.ex
Broken out from #455
Prepping to move these out to a separate module by proving that they're only used from here.
=> Make preflight helper functions private

lib/mix/nerves/utils.ex
This simplifies checking for the availability of certain binaries and giving an appropriate error message saying which package to install if it's missing.
Broken out from #455
=> Extract ensure_available!/2 preflight helper

lib/mix/nerves/preflight.ex, lib/mix/nerves/utils.ex, lib/mix/tasks/burn.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.image.ex
Note that the function name was change from `Mix.Nerves.Utils.preflight/0` to `Mix.Nerves.Preflight.check!/0`. This was technically a public function but I'm assuming that this isn't an API anyone is using, so I didn't leave a deprecated stub in the `Utils` module. Let me know if you prefer for it to stay there.
Split out from #455
=> Move Mix task preflight checks to a module

lib/nerves/release.ex
The existing bootscripts may be helpful to other functions in the release steps, lets not remove them.
=> Do not clear out the existing bootscripts

lib/nerves/artifact.ex, lib/nerves/env.ex, test/nerves/env_test.exs, test/support/test_case.ex
This also adds support for XDG_DATA_HOME as described in  https://github.com/elixir-lang/elixir/pull/8933
This is going to require some documentation but I wanted to start the discussion on the variable name. Considering that the subcomponents of this could be set via `NERVES_DL_DIR` and `NERVES_ARTIFACTS_DIR` I chose to fix the existing but broken `data_dir/0` function and call it `NERVES_DATA_DIR`.
=> Add NERVES_DATA_DIR to specify global nerves data location

docs/Advanced Configuration.md, lib/mix/tasks/firmware.ex, lib/nerves/erlinit.ex, test/nerves/erlinit_test.exs
The options from the system are merged with the options specified in `Application.get_env(:nerves, :erlinit)`. If there are overrides, a new erlinit.config file is generated and placed in a new _build  rootfs_overlay directory. This path is passed to rel2fw and will be overridden by the project level rootfs_overlay files.
Here is an example:
If we have a Raspberry PI 3 and in our `config/target.exs` put 
```elixir
config :nerves, :erlinit,
ctty: "ttyAMA0"
```
The generated config will send the terminal output to the serial port.
There are a few caveats with this approach.
* Options that accumulate can not be overridden, they can only be appended. For example, multiple `--mount`.
* Other options can be removed if a value is already specified by setting the value to `nil` or `false` in the …
=> Allow erlinit options to be merged from mix config

lib/nerves/erlinit.ex, test/nerves/erlinit_test.exs
This fixes and adds unit tests to the following erlinit.config override
support:
* Handle string values with spaces - previously they were split and
appeared as separate options to erlinit when they were not. This
affected `:alternate_exec` in particular.
* Handle trailing comments - previously an inline comment could be
included in the value
* Trim whitespace - previously leading whitespace could cause parameters
to be ignored. Whitespace in other places could also lead to weirdness
with values.
* Quote strings with spaces when encodeding - previously, they weren't
quoted and that would mess up erlinit (understandably)
This also converts the encoder to construct the result using iodata for
the intermediate work. The iodata is flattened at the end to a string to
avoid changing APIs.
=> Fix erlinit option parsing/formating issues

lib/nerves/env.ex
Depending on base dir does not allow the `XDG_DATA_HOME` env variable to override the location of the data directory.
=> Do not depend on base dir

lib/mix/tasks/burn.ex, test/nerves/mix_test.exs
This will update the task to allow calling `mix burn --firmware /path/to/app.fw`
=> Allow the path to the fw to be passed to mix burn

lib/mix/tasks/firmware.unpack.ex
This command unpacks generated `.fw` files so that it's easy to inspect
the root filesystem and other .fw information on the host system.
Here's an example:
```sh
$ mix firmware.unpack
Nerves environment
MIX_TARGET:   rpi0
MIX_ENV:      dev
Unpacking to circuits_quickstart-rpi0...
Archive:  /Users/fhunleth/nerves/circuits/circuits_quickstart/_build/rpi0_dev/nerves/images/circuits_quickstart.fw
inflating: /Users/fhunleth/nerves/circuits/circuits_quickstart/circuits_quickstart-rpi0/meta.conf
inflating: /Users/fhunleth/nerves/circuits/circuits_quickstart/circuits_quickstart-rpi0/data/bootcode.bin
inflating: /Users/fhunleth/nerves/circuits/circuits_quickstart/circuits_quickstart-rpi0/data/fixup.dat
inflating: /Users/fhunleth/nerves/circuits/circuits_quickstart/circuits_quickstart-rpi0/data/sta …
```
=> Add "mix firmware.unpack"

lib/mix/tasks/firmware.image.ex
Invocations of "mix firmware.image" call "mix firmware" implicitly with
this change to avoid situations where the image is made from stale
firmware.
This is analogous to "mix firmware.burn" also calling "mix firmware"
implicitly.
=> Build the firmware for mix firmware.image

lib/mix/nerves/shell.ex, lib/mix/nerves/utils.ex
This fixes a few of the (sadly) many Dialyzer warnings.
The only nontrivial one is the version parsing. Since `Version.parse/1`
doesn't return an error tuple (it just returns `:error`), Dialyzer would
complain that a lone `:error` atom would need to be handled as well. It
looks like the regular expressions should prevent errors from being
returned in practice, so I changed the parsing to raise should the
regular expressions miss anything.
=> Fix Dialyzer warnings

lib/nerves/artifact.ex, test/nerves/artifact_test.exs
This fixes the issue where mix deps.get would try to fetch the artifact even though it has already been downloaded.
=> Fix issue with artifact base_dir expansion.

lib/nerves/erlinit.ex, test/nerves/erlinit_test.exs
If NERVES_SYSTEM is set, look for the erlinit.config file in the system override location instead of the package path.
=> Update erlinit config path for system env var

lib/mix/tasks/burn.ex, lib/mix/tasks/firmware.ex, lib/nerves/env.ex, test/nerves/env_test.exs
This cleans up some code duplication, adds a couple tests, and exposes a place for 3rd party tools to locate firmware build files.
=> Refactor images_path to centralize in Nerves.Env

lib/mix/tasks/firmware.metadata.ex
It's useful to find out the firmware UUID to match against what's
running on device. This adds a task to do it rather than having to type
`fwup -m -i <path to .fw>`.
=> Add firmware.metadata task

lib/nerves/env.ex, test/nerves/env_test.exs
64-bit ARM machines previously were falling through the x86_64-catchall.
This adds an entry for them since they'll likely appear more often going
forward.
=> Support the aarch64 architecture

.circleci/config.yml, README.md, docs/Installation.md, lib/nerves.ex, lib/nerves/env.ex, lib/nerves/package/utils/squashfs.ex, mix.exs, test/nerves/env_test.exs, test/nerves/mix_test.exs, test/nerves/utils_test.exs, test/support/test_case.ex
Add support for Elixir 1.10.
This mainly updates the test suite to accommodate for upstream changes in the Mix test suite. This was tested on a rpi0.
This also bumps the "official" versions in the docs to elixir 1.10.2 and OTP 22.2.8
=> Elixir 1.10

lib/nerves/erlinit.ex, test/nerves/erlinit_test.exs
This reverts commit 5ef228de51f18f85fa38797ceef0bd17d7729d2b.
Turns out this doesn't work. The `rootfs_overlay` is unavailable in the system artifact and this commit causes the erlinit.config Mix override to break.
=> Revert "Update erlinit config path for system env var"

lib/mix/nerves/preflight.ex
While most users won't need 1.5, updating to it brings in fixes and
includes GPT and SOURCE_DATA_EPOCH support which will be nice to expect.
Fwup 1.5 was released November 16, 2019.
=> Require fwup 1.5 or later

README.md
70065de93b4159b9926000bce2587643305e2072 moves CONTRIBUTING.md .
But the link of 'Contributing Guide' keeps old.
=> Update /CONTRIBUTING.md to /.github/CONTRIBUTING.md on README.md

lib/nerves/env.ex, test/nerves/artifact/resolver_test.exs, test/nerves/artifact_test.exs, test/nerves/build_runner/docker_test.exs, test/nerves/cache_test.exs, test/nerves/env_test.exs, test/nerves/erlinit_test.exs, test/nerves/integration_test.exs, test/nerves/mix_test.exs, test/nerves/utils_test.exs, test/nerves/utils_wsl_test.exs, test/support/test_case.ex
Nerves integrates with Mix and therefore needs to reset the environment each time its done with a test run. Ensure all tests are done in series to prevent the environment from being clobbered.
Fixes https://github.com/nerves-project/nerves/issues/502
=> Serialize all tests

docs/Installation.md
Since switching to `nerves_pack`,`vintage_net_wifi` is included by default and requires pkg-config to be installed on the host system.
Fixes:
```
==> vintage_net_wifi
Makefile:53: *** pkg-config required to build. Install by running "brew install pkg-config".  Stop.
could not compile dependency :vintage_net_wifi, "mix compile" failed. You can recompile this dependency with "mix deps.compile vintage_net_wifi", update it with "mix deps.update vintage_net_wifi" or clean it with "mix deps.clean vintage_net_wifi"
```
=> Add pkg-config to installation instructions

docs/Customizing Systems.md, lib/mix/tasks/firmware.ex, lib/nerves/env.ex
For https://github.com/nerves-project/nerves/issues/395
See https://github.com/nerves-project/nerves/issues/395#issuecomment-607398618 for more info.
This allows a local, uncompiled system to pass the Env check so that it can be run through the precompile check later on. This will give a better warning if the system has not be compiled, or will trigger compilation if the `nerves: [compile: true]` option is enabled in the dependency
=> Handle local system compilation via mix.firmware

lib/mix/tasks/nerves.artifact.ex
I noticed `nerves.artifact` task was checking for a stale artifact, but
that is now handled in `nerves.precompile` called earlier in the task so
this cleans up that check a bit
=> Remove stale check in nerves.artifact

docs/Installation.md
ASDF uses curl to download Kerl. It was found that on a fresh install of Ubuntu 19.10, curl was not installed by default.
=> Add curl to the installation instructions

README.md
nerves-project.org changed which means the assets for these images changed.
So this updates them and fixes a couple other links as well
=> Update sponsor images

.circleci/config.yml, docs/Installation.md
Fixes https://github.com/nerves-project/nerves/issues/516
=> erlang/otp: bump to v22.3.2 in install  doc

lib/nerves/artifact/resolvers/github_api.ex, test/nerves/artifact/resolver_test.exs
Artifact resolvers should never raise and instead they should try their best and present a relevant warning if they are unsuccessful. This updates the Github API artifact resolver to pass back a warning instead of raising. This allows CI builds to skip over the resolvers without having to do additional work in the mix file.
=> Prevent github api resolver from raising

lib/nerves/release.ex
This will clear out the release directory and prevent it from accumulating upgraded libraries / unnecessary OTP applications over time.
=> Clean the release directory

docs/Targets.md
Hey y'all,
I was reading through the Nerves pages on HexDocs, and came across this weird link in the [Targets](https://hexdocs.pm/nerves/targets.html#content) page under the [Supporting New Target Hardware](https://hexdocs.pm/nerves/targets.html#supporting-new-target-hardware) header:
> See [create-build.sh variable in NERVES_BR_VERSIONthe](https://github.com/nerves-project/nerves_system_br/blob/master/create-build.sh).
I took a peek at the `docs/Target.md` file to see what's up and everything looks fine there:
> See [the NERVES_BR_VERSION variable in create-build.sh](https://github.com/nerves-project/nerves_system_br/blob/master/create-build.sh).
I generated the docs locally to see what would happen, and ended up with the same weird link as above.  Maybe an ExDoc bug? In the meantime, I …
=> Resolve strange link behavior in documentation

docs/Experimental Features.md, lib/mix/nerves/preflight.ex, lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.patch.ex
This PR adds the mix task `mix firmware.patch` for testing patchable firmware files. I've added a bit of documentation about it under an "Experimental features" section since the system requirements and workflow for creating firmware patches may change.
=> Add support for creating firmware patches in mix tasks

mix.exs
We have this doc, but it doesn't show on hexdocs.pm
Is this on purpose? If not, here's the change. Once merged we can do `mix hex.publish docs` to just push this up for use
=> add Experimental Features to docs when publishing

src/Makefile
This fixes the following error:
```
** (Mix) Nerves encountered an error while checking host requirements for fwup
{"", 8}
Please open a bug report for this issue on github.com/nerves-project/nerves
```
This happens when you use the `nerves-env.sh` way of loading environment
variables for crosscompilation. The `port` program gets compiled for the
target, but it's meant to run on the host. This switches the Makefile to
reference the host versions of the tools. The names for these are
`*_FOR_BUILD` since that's what's used in Buildroot and autoconf.
This requires https://github.com/nerves-project/nerves_system_br/pull/480.
=> Use host CC to compile port

.circleci/config.yml, lib/nerves/release.ex, mix.exs, test/fixtures/release_app/config/config.exs, test/fixtures/release_app/mix.exs, test/nerves/mix_test.exs
This fixes rootfs priority file creation logic that was broken when removing distillery, adds a end to end test.
=> Fix rootfs_priorities file creation and add test

lib/nerves/erlinit.ex, test/nerves/erlinit_test.exs
OptionParser silently drops options that it doesn't know. This is a
"feature" since options are turned into atoms and the Erlang VM doesn't
GC atoms. However, this is not a feature for `erlinit` since it prevents
possibly valid options from making their way to the target. Exhausting
the atom pool is not an issue, since this is a compilation tool and not
a long-lived server.
=> Don't silently drop unknown erlinit options

docs/Advanced Configuration.md, lib/nerves/erlinit.ex
The `:shutdown_report` option lets you specify a path that `erlinit` can
use to write a report on why the system powered off or rebooted. This
report can be useful when debugging unexpected exits from the Erlang VM.
=> Add :shutdown_report to erlinit options

lib/mix/nerves/preflight.ex
While most users won't need 1.8, updating to it brings in useful fixes for autodetecting SDCards and
verifying writes. It also brings in VCDIFF support which will be useful
as people start experimenting with binary diff firmware updates.
Fwup 1.8.1 was released July 15, 2020.
=> Require fwup 1.8 or later

README.md
According to the release note, the minimum supported version of Elixir is now version 1.9.
And also, WSL "2" is recommended when we use Windows as the host.
=> Require Elixir 1.9 or later (from Nerves v1.7.0)

docs/FAQ.md
This list is no longer available on the main website.
Fixes #560
=> Remove link to community-maintained libraries from FAQ

lib/mix/tasks/compile.nerves_package.ex
I haven't done any Nerves in long time, and the updates are awesome. I did get a bit confused by this messaging when trying to debug creating firmware in an Umbrella project though. The problem was that I was not importing the generated `config.exs` file. (Umbrella projects no longer import the application configs by default.)
I thought this might help someone else.
The wording of the  current advice implies that the code has detected that `mix firmware` (or `compile`) is taking place in the base of the umbrella project, and that the fix is to cd into an application and try from there.
In fact `in_umbrella/1` will return true in an umbrella project even if  `mix firmware` is being invoked in application directory. When I checked, the working directory (`File.cwd!`) at this point is in the …
=> Change error advice around compilation issues, especially from an Umbrella project

docs/User Interfaces.md
I removed trailing comma in a sample code to prevent syntax error when copy-and-pasted.
=> Fix a documentation error in `docs/User Interfaces.md`

lib/nerves/utils/wsl.ex
Docker Desktop for Windows uses WSL 2 kernel as the back-end. 
`/.Dockerenv` exists in the environment where Docker container is running.
We can use this file to check whether the environment is Docker or WSL 2 shell before checking the kernel name from `/proc/sys/kernel/osrelease`. 
This PR will fix #568
=> check whether the env is Docker or WSL 2 shell

scripts/docker/nerves_system_br/noninteractive-build.sh
If a source code repository or the URL to it is broken, this change will
catch that error at the beginning of the build. This saves quite a bit
of time waiting for a build to complete only to find out that one of the
last packages to build fails due to a download issue.
=> Run 'make source all' to catch download issues first

lib/nerves/artifact/build_runners/docker.ex
I found the following page with unorganized format.
https://hexdocs.pm/nerves/Nerves.Artifact.BuildRunners.Docker.html#module-images
My PR makes this example code displayed as a block. (checked by `mix docs` locally)
=> Minor fix for HexDocs

lib/mix/tasks/firmware.ex, lib/mix/tasks/firmware.patch.ex, lib/nerves/artifact/cache.ex, lib/nerves/artifact/resolver.ex, test/fixtures/host_tool/lib/host_tool/platform.ex, test/nerves/cache_test.exs
This updates all of the unchecked calls to `File.mkdir_p` so that
they raise on error. This is ok, since `mkdir_p!` doesn't raise if the
directory already exists. If the directory can't be created, though,
this now fails immediately rather than at some other place where you
have to infer what the problem was.
=> Always call mkdir_p! to catch errors

mix.exs
The Elixir requirement string in the `mix.exs` was out of date and
allowed Elixir versions that don't work with Nerves. This updates the
check to require 1.9.4, 1.10.x, and ~> 1.11.2.
Reasoning:
1. Elixir versions prior to 1.9 don't work since mix releases are
required. Distillery support was removed from Nerves 1.7.0
2. Elixir 1.9.4 is required since that's what we test with on CI. Anyone
stuck on Elixir 1.9 hopefully can upgrade to 1.9.4.
3. All Elixir 1.10 versions seem to work, so they're all allowed.
4. Elixir 1.11.0 doesn't work due to a mix target issue.
5. Elixir 1.11.1 doesn't work due to an issue with recursive aliases
that affects poncho projects
6. Elixir 1.11.2 and later versions work
This addresses #583. Note that Elixir only gives a warning when this check fails.
=> Update Elixir version requirements

lib/nerves/utils/http_client.ex
This adjusts the User-Agent header to respect RFC7231.
[Intended to be merged after PR #591]
=> Fix User-Agent per RFC7231

docs/Experimental Features.md, lib/nerves/env.ex, lib/nerves/package.ex, test/fixtures/system/mix.exs, test/nerves/env_test.exs
Packages can provide custom system environment variables to be exported when
`Nerves.Env.bootstrap/0` is called. The initial use case for this feature is to
export system specific information for llvm-based tools. Here is an example from
`nerves_system_rpi0`
```elixir
defp nerves_package do
[
env: [
{"TARGET_ARCH", "arm"},
{"TARGET_CPU", "arm1176jzf_s"},
{"TARGET_OS", "linux"},
{"TARGET_ABI", "gnueabi"}
]
]
end
```
=> Add env to package and export during bootstrap

lib/mix/tasks/nerves.artifact.ex, lib/mix/tasks/nerves.artifact.get.ex
This also turns off the docs for `nerves.artifact.get` since this is
better called via `mix deps.get`.
=> Clarify artifact mix tasks 

README.md, docs/Compiling Non-BEAM Code.md, mix.exs
I couldn't find that we ever documented all of the environment variables that we set for building C/C++ code, so I started writing one.
=> Add section for compiling non-BEAM code

CHANGELOG.md, lib/nerves/artifact/resolvers/github_api.ex, lib/nerves/utils/http_client.ex, test/nerves/artifact/resolver_test.exs, test/support/test_server/router.ex
=> Bug fix for double encoding of URL query parameters in OTP-23.2+

docs/Installation.md
These versions will match the 1.15.0-based official systems that were
just published.
=> Bump Erlang and Elixir versions

test/nerves/cache_test.exs, test/nerves/env_test.exs
Fixes up tests running on CI by unsetting environment variables prior to assert.
=> Clean env before running tests

docs/Installation.md
Following the 1.7.5 release documentation for [Customizing Your Own Nerves System](https://hexdocs.pm/nerves/customizing-systems.html#getting-setup-to-build-a-system) and had errors ( warnings ) about SSL in erlang 23.1.*.
[Conversation available in slack.](https://elixir-lang.slack.com/archives/C0AB4A879/p1619304867115500)
This doesn't fix the autogenerated hexdocs for v1.7.5, but I noticed the installation.md on main was out of date from my experience and I couldn't build earlier than 23.3.* successfully. So I'm tossing this PR anyways.
Thanks.
=> Bump erlang version

.circleci/config.yml, mix.exs
Elixir 1.12.0-rc.1 appears to work fine, so remove the warning that
Nerves can't use it.
=> Support Elixir 1.12.0-rc.1

docs/User Interfaces.md
This simply adds missing urls to the exiting links for `nerves_pack`, `vintage_net`, and `vintage_net_direct` documentation in the "Configure Networking" section of the User Interfaces guide.
=> Docs: Fix link to nerves_pack and vintage_net documentation

lib/nerves/artifact.ex, lib/nerves/env.ex
The directory used by `Nerves.Env.data_dir` is not $HOME, but $XDG_DATA_HOME which is different on some Linux distributions. Updated the artifacts directory docs to note this as well.
=> Docs: clarify location of artifacts directory

.circleci/config.yml, lib/mix/tasks/firmware.ex
The current compiler version check would compare the results from
looking at the compiler version from an OTP  module and comparing it to
an Elixir one. This worked until OTP 24 where the OTP modules are marked
with OTP's bootstrap compiler's version number and that version number
is a major number different from the non-bootstrap compiler's version
number.
Whether or not this is an OTP bug, it seems like asking the `:compiler`
application for its version number rather than consulting an OTP BEAM
file is just as valid. This PR changes the check to be "Is the current
:compiler version number compatible with whatever compiled Elixir?"
While making the change, I took the opportunity to simplify the code by
removing error checks that I couldn't figure out how to trigger without
something …
=> Update Erlang compiler version check for OTP 24

lib/nerves/artifact.ex
OTP 24 returns 'aarch64-apple-darwin20.4.0' for the system architecture.
Previous OTP versions returned 'arm-apple-darwin20.4.0'. The toolchain
filename is constructed from the first word in the triple, so toolchains
started failing of M1 Macs.
This is a quick workaround that normalizes the name to the old way.
=> Fix toolchain downloads for Apple M1/OTP 24

docs/Installation.md
The current nerves versions and systems require OTP 24 to avoid the host and target have different OTP versions error, so the installation guide should be updated as well.
Reported on slack
=> Update installation doc Elixir/OTP versions

lib/mix/tasks/firmware.gen.gdb.ex, mix.exs, priv/templates/script.run-gdb.sh.eex
This is required for programs like `gdb`, `debuginfod` and similar to automatacally locate debug symbols when present
=> Add new mix task for generating a gdb wrapper script

Makefile
The gcc commandlines and other prints can be useful, but most of the
time they are overwhelming especially for non-C programmers. This
simplifies the prints.
To re-enable, set `V=1` like is common with many Makefile/C projects.
For example `V=1 make`, `V=1 mix compile`, etc.
=> Reduce Makefile/gcc prints to clean build output

docs/Advanced Configuration.md
Related to nerves-project/nerves_system_br#570
This PR adds documentation for how to use `sysctl` to configure kernel parameters, which was introduced in nerves-project/nerves_system_br#570.
=> Add docs for configuring kernel parameters

lib/mix/tasks/firmware.unpack.ex
On some systems (Arch Linux) xattrs needs additional permissions. Since
`mix firmware.unpack` is intended as a debug tool, having accurate
xattrs hardly seems important so this disables them.
=> Don't set xattrs when unpacking archives

docs/Installation.md
Updated Ubuntu installation instruction for newer Ubuntu versions.
As per https://askubuntu.com/questions/1241217/package-libwxgtk3-0-dev-has-no-installation-candidate-on-ubuntu-20-04 - the package was renamed from libwxgtk3.0-dev to libwxgtk3.0-gtk3-dev.
Tested on Windows 10 + WSL2 with Ubuntu 20.04
=> Update Ubuntu installation instructions.

scripts/docker/nerves_system_br/noninteractive-build.sh
This standardizes on using `env` to find the shell executable and also
`bash`.
=> Make shebang consistent across Nerves

docs/Targets.md
The RPI Zero 2 W is listed as supported by nerves_system_rpi3a as of
https://github.com/nerves-project/nerves_system_rpi3a/releases/tag/v1.17.2
=> Add rpi3a (for zero 2) to list of targets

docs/Getting Started.md
This link is a bit easier to scan than the existing link that is within the text.
=> Add an additional link to the targets page

lib/nerves/package.ex
This function is deprecated in 1.13, and it looks like it was only to
support a deprecated feature anyway. The unit tests didn't need to be
changed so this code wasn't tested..
=> Remove Mix.Config.persist reference

lib/mix/tasks/firmware.ex
This adds a short message for what to do next after running `mix
firmware`. The goal is to have a simple reminder for what to do next.
It looks like this:
```sh
...
Building /Users/fhunleth/git/nerves-project/nerves_examples/blinky/_build/rpi0_dev/nerves/images/blinky.fw...
Firmware built successfully! 🎉
Now you may install the firmware on a MicroSD card using `mix burn` or upload
the firmware to a device with `mix upload` or `mix firmware.gen.script`/`./upload.sh`.
```
=> Add firmware build success message

lib/nerves/utils/http_client.ex, mix.exs, mix.lock
With OTP 24, it now warns you when attempting an HTTPS request without any verification, although TLS still allows it.
This takes the hint to get a little more secure when downloading Nerves artifacts and attempts to establish authenticity from trusted certs in `:castore`, which should include the most common github release downloads
=> Verify artifact downloads

lib/nerves/artifact.ex
A bug in the toolchain was causing a non-string to be passed around as
the error. This would give a stack trace when trying to print the error.
This is fixed now. However, in retrospect, having quotes around the
error message looks better and inspecting the error bulletproofs it
anyway.
=> Inspect error in case non-strings passed

lib/mix/tasks/nerves.artifact.get.ex
It wasn't obvious whether errors downloading artifacts were a problem or
not. This is an update to the wording to give more information on what's
happening.
The key changes were to refer to the artifacts as prebuilt versions and
to change the error message from "no_result" to "Prebuilt xyz not
found".
Here's the before:
```
==> nerves_system_rpi0
Resolving Nerves artifacts...
Resolving nerves_system_rpi0
=> Trying
https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.18.0/nerves_system_rpi0-portable-1.18.0-792C09C.tar.gz
Status 404 Not Found
=> Trying
https://github.com/nerves-project/nerves_system_rpi0/releases/download/v1.18.0/nerves_system_rpi0-portable-1.18.0-792C09C4B63C061CB451646DC01DD20DB8BB676441E531E9FA5AF9BE8C4AC5BC.tar.gz
Status 404 Not Found
=> no_result …
```
=> Update wording when downloading artifacts

docs/Compiling Non-BEAM Code.md
- Remove erl_interface references since removed in OTP 23
- Add minimum nerves_system_br version for buid env
=> Add minimum nerves_system_br version for buid env

docs/Advanced Configuration.md, docs/Compiling Non-BEAM Code.md, docs/Customizing Systems.md, docs/Experimental Features.md, docs/FAQ.md, docs/Getting Started.md, docs/Installation.md, docs/Internals.md, docs/Systems.md, docs/Targets.md, docs/Updating Projects.md, docs/User Interfaces.md, docs/Using the CLI.md
Making it easier for community contribution,
this is similiar to the link at the bottom of Elixir guides like
https://elixir-lang.org/getting-started/introduction.html
=> Add doc link to "Edit this page on GitHub"

docs/Compiling Non-BEAM Code.md, lib/nerves/package.ex, test/fixtures/system/mix.exs, test/nerves/env_test.exs
This makes it possible to pass custom flags to all of the gcc tools
generically rather than update `CFLAGS`, etc. individually.
Here's an example for the RPi3a:
```elixir
{"TARGET_GCC_FLAGS", "-mabi=aapcs-linux -mfpu=neon-vfpv4 -marm -fstack-protector-strong -mfloat-abi=hard -mcpu=cortex-a53 -fPIE -pie -Wl,-z,now -Wl,-z,relro"}
```
This enables NEON and VFPv4 support (default is VFPv3 w/ 16 registers). There are other changes from the default toolchain options so that the NIF and port compilation is consistent with Buildroot. Things like the ABI happen to be the defaults, though.
=> Add TARGET_GCC_FLAGS to pass custom gcc flags

lib/nerves/env.ex, lib/nerves/package.ex
This fixes an issue where the TARGET_GCC_FLAGS were applied too early
and they missed some CFLAGS being set by the Nerves system.
This fixes a compiler error finding `libmnl` include files.
=> Delay applying TARGET_GCC_FLAGS to CFLAGS

lib/mix/tasks/firmware.ex
Nerves checks that the version of Erlang used to compile Elixir is
compatible with the one that will be used. The error message says that
the major version number needs to be the same and this makes sense. The
check, however, was that Elixir had to be compiled using an Erlang
compiler major/minor that was the same or later than the currently used
one.
Erlang/OTP 24.3 bumped the compiler's minor version so this error gets
generated:
```
** (Mix) Elixir was compiled by a different version of the Erlang/OTP compiler
than is being used now. This may not work.
Compiler used for Elixir: 8.0.4
Current compiler:         8.1.0
```
This is not a problem, so this change simplifies the version check to
compare major numbers just like the error message says.
For posterity, here is the release note for …
=> Relax Erlang compiler check

docs/Installation.md
I've narrowed and tested the packages required to build firmware with Nerves. This brief description covers how to use them with `nix-shell` (on any linux based system with Nix package manager) or by including them in the `configuration.nix` file of a NixOS system. 
I tested that the build inputs work as expected on a clean nix instance on replit.com to make sure none of my host system's installed packages could cause false positives. 
Hopefully, this description makes sense and adds value to the Nerves installation docs. Please feel free to ask questions or make suggestions for changes. 
One thing I wasn't sure about, which you may want to change, is the addition of a heading above the note "For other linux host distributions...". It seems like it's easily lost as it blends with the text …
=> Adding installation instructions for NixOS and Nix package manager

lib/nerves/artifact.ex
When the error message is a string, calling `inspect` on it limits it to
50 chars, which often ends up being something like
```
"[output of configure]" <> ...
```
and doesn't show the actual error.
=> artifact.ex: Print string errors instead of &inspect/1

lib/nerves/utils/http_client.ex
We are seeing issue with TLS fetching from S3 in CI with the following error:
```
21:26:41.176 [info]  TLS :client: In state :certify at ssl_handshake.erl:1952 generated CLIENT ALERT: Fatal - Handshake Failure
- {:bad_cert, :max_path_length_reached}
```
Setting the ssl `depth` parameter to `3` like recommended in https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/ssl fixes the issue.
=> add ssl parameter depth 3 to http_opts

lib/nerves/artifact.ex, lib/nerves/env.ex, lib/nerves/package.ex, lib/nerves/release.ex
- Fix package environment spec
- Use iodata and remove unneeded join
- Simplify Enum.reject for credo
- Use iodata for creating priorities file
=> More credo and dialyzer fixes

test/fixtures/host_tool/mix.exs, test/fixtures/integration_app/mix.exs, test/fixtures/package/mix.exs, test/fixtures/package_build_runner_opts/mix.exs, test/fixtures/package_build_runner_override/mix.exs, test/fixtures/simple_app/mix.exs, test/fixtures/simple_app_artifact/mix.exs, test/fixtures/system_artifact/mix.exs, test/fixtures/toolchain/mix.exs, test/fixtures/umbrella/apps/toolchain/mix.exs
These aren't needed, so delete all calls.
=> nerves_bootstrap automatically calls add_alias

lib/mix/tasks/nerves.info.ex, lib/nerves.ex, lib/nerves/env.ex, test/nerves/env_test.exs
Mix already checks for a compatible version of Elixir and the Nerves
system does a very specific check on the version of Erlang. Therefore
the check here is redundant as well as not being as easy to maintain as
the other checks.
=> Remove Elixir/Erlang version check

lib/mix/nerves/io.ex, lib/mix/tasks/nerves.clean.ex, lib/mix/tasks/nerves.deps.get.ex, lib/mix/tasks/nerves.env.ex, lib/mix/tasks/nerves.loadpaths.ex, lib/mix/tasks/nerves.precompile.ex, lib/mix/tasks/nerves.system.shell.ex, lib/nerves/artifact.ex, lib/nerves/env.ex, mix.exs
Companion PR to https://github.com/nerves-project/nerves_bootstrap/pull/225
Moves all the tasks and tooling into `:nerves` package to help simplify
maintenance and execution. This PR simply copies the tasks over and does
not alter functionality.
=> Move tooling from Nerves.Bootstrap into Nerves 

README.md, docs/Targets.md
We now officially support GRiSP2, adding [nerves_system_grisp2](https://github.com/nerves-project/nerves_system_grisp2).
* Add NervesSystemGrisp2 to the Hardware section in README.md
* Add `grisp2` to the Supporded Targets and Systems documentation
=> Update documentation for GRiSP 2 Support

lib/nerves/env.ex
This fixes an issue where the flags could smash together if not careful
and amazingly this didn't cause an error.
=> Add space between system CFLAGS and environment flags

lib/mix/tasks/nerves.artifact.details.ex, lib/mix/tasks/nerves.artifact.name.ex
Fixes #771
This fix adds a mix task `mix nerves.artifact.name` which display various artifact  names/information w/o triggering a artifact re-build.
Example:
```
$ mix nerves.artifact.name
==> nerves
==> nerves_system_bbb
Generated nerves_system_bbb app
Nerves environment
MIX_TARGET:   target
MIX_ENV:      dev
Name:               nerves_system_bbb-portable-2.15.1
Download Name:      nerves_system_bbb-portable-2.15.1-0C8DD7C
Download File Name: nerves_system_bbb-portable-2.15.1-0C8DD7C.tar.gz
Download Path:      /home/udos/.nerves/dl/nerves_system_bbb-portable-2.15.1-0C8DD7C.tar.gz
Checksum:           0C8DD7CEB69659D7486BBA6B22AE1CB498EF3487A5369411F0C157477F8FF2D0
```
=> Add mix task to display artifact name/information

docs/Getting Started.md, lib/mix/tasks/firmware.burn.ex
Large part of the "Getting Started" page is 3-6 years old as of 2022. While most information there is still useful, we could polish it for relevance to current Nerves and audience.
This pull request focuses on the top half of the "Getting Started" page. I kept the changes minimal.
The changes I made is totally subjective. I would like input from you all.
- move mix command snippets closer to where they are explained about
- move extra `mix firmware.burn` options to its doc
- reason: details can be noise from the beginners perspective
- replace `rpi3` with `rpi0` in snippets 
- reason: assumption that many Nerves enthusiasts use `rpi0` these days
- clean code snippets so that they can be copy-paste'd easily
=> Update "Getting Started" page (top half)

docs/Using the CLI.md, mix.exs
This link is used in NervesMOTD and possibly other places. The CLI docs
moved, so this directs the user to the new place until the links can all
be updated.
=> Add "Using the CLI" link to point to new location

mix.exs
build_embedded isn't needed here and probably will be removed in Elixir
1.15.
=> Remove build_embedded

docs/Installation.md
When following the 'Getting Started' documentation as is, you will get a host mismatch error when using the 'rpi0' target, as https://github.com/nerves-project/nerves_system_rpi0 uses OTP 25 since v1.19.0
=> Updating OTP version of Elixir install to 25

docs/Getting Started.md
Nerves automatically caches Nerves artifacts that are downloaded for our Nerves projects for our convenience. As time progresses, it may result it a pile of old unused Nerves artifacts in our development host machine.
How about show the Nerves users how to delete those archives?
Add a pro tip box with a brief explanation
=> Add a tip of deleting cached artifacts

test/nerves/cache_test.exs
This test has been plaguing our CI runs forever by sporadically and inconsistently failing. The failing test expects a corrupted system download to be deleted and not exist, but sometimes fails because the file is there. It turns out that during this particular file check, we first look for `NERVES_SYSTEM` to be set and use that path if it exists. We just so happen to set that environment variable in other tests to a valid system file and there is a race between that env var being cleaned up and this test running while processing tests asyncronously, which is why it works for some seeds and not for others.
This forcefully deletes that env var before running the test to ensure the expected corrupted test file gets picked up by the tooling instead and cleaned up as expected
=> Fix sporadically failing cache_test.exs

docs/Advanced Configuration.md, docs/FAQ.md, docs/User Interfaces.md, test/fixtures/umbrella/config/config.exs
[Mix.Config](https://hexdocs.pm/mix/Mix.Config.html) has long been deprecated. Let's use [Config](https://hexdocs.pm/elixir/Config.html) instead per Elixir doc.
Also, I removed kind of redundant `import Config` in our example config snippets. I thought it was confusing since we do not need to add it to the existing file. `import Config` is so idiomatic that the user will figure out.
=> Remove deprecated Mix.Config

docs/Connecting to Nerves Target.md, docs/FAQ.md
Currently the instructions for overriding default console settings is in the Frequently-Asked Questions page and it seems confusing and overcomplicating to me. At least a few Nerves users around me had trouble understanding how to enable the UART serial console for `rpi3`.
I thought it would be nice to limit the explanation about `erlinit` to the simplest.
- Move the "Using a USB Serial Console" FAQ topic to "Connecting to Nerves Target" page and simplify the explanation.
--- 
---
- We could make a dedicated page for `erlinit` if needed.
- Other FAQ contents can be moved under some context so that they can be easy to discover.
=> Simplify explanation for overriding default console settings

docs/Customizing Systems.md
With everything on one line the doc cannot be read without horizontal scrolling. This makes it particularly hard to read on smaller screens.
On smaller screens the docs currently look like this:
And on larger screens it looks like this:
This is what it looks like after:
=> Update custom system doc dep line-breaks

lib/mix/tasks/firmware.ex
For https://github.com/nerves-project/nerves/issues/576
This allows us to use the build path for the specific target/env when compiling the firmware. Requires https://github.com/nerves-project/nerves_system_br/pull/674
=> Include `MIX_BUILD_PATH` in the firmware build process

lib/nerves/artifact.ex, test/nerves/artifact_test.exs
In the very beginning, artifacts were stored in releases with their full checksum value. Now they are stored with the 7 byte checksum shorthand, but we still try to request both.
I think its been long enough using the shorthand that we can remove this second request which should clear up the logs a bit and make it less confusing when an artifact can't be found
Also, the work in #822 should provide better output when artifacts can't be found which would help as well
=> Remove duplicate artifact request

lib/nerves/artifact.ex, lib/nerves/artifact/resolvers/github_api.ex, test/nerves/artifact/resolver_test.exs, test/nerves/artifact/resolvers_github_api_test.exs, test/nerves/artifact_test.exs, test/support/test_http_client.ex
* Switches `:github_releases` artifact site to also use `Resolvers.GithubAPI`
* `Resolvers.GithubAPI` has been totally refactored
* Fixed issue with errors reporting to use `GITHUB_TOKEN`, but that env var would never actually be used in the code
* Supports `GITHUB_TOKEN` or the `GH_TOKEN` shorthand that GitHub also supports
* Adjusted errors to better report the situation discovered
* No release
* Release found but no artifacts * Artifacts found, but none with matching checksum * Missing token when unable to authenticate a GitHub request to private repo
=> Refactor GitHub artifact fetching

test/nerves/artifact_test.exs
If a user has `NERVES_ARTIFACTS_DIR` set locally, these tests will fail so delete it before the test runs for good measure
=> Remove `NERVES_ARTIFACTS_DIR` when testing artifact base_path

lib/nerves/artifact/resolvers/github_api.ex, test/nerves/artifact/resolvers_github_api_test.exs
The GithubAPI resolver will crash if someone passes `token: nil` so this handles that case and allows the error later on to report what was wrong
=> Handle a nil token with GithubAPI resolver

docs/Installation.md
Add `pkg-config` dependency to the `shell.nix`.
pkg-config is needed to build the firmware.
=> Add missing pkg-config dependency to shell.nix

lib/nerves/artifact.ex, test/nerves/artifact_test.exs
Using the GitHubAPI resolver for github releases exposed another issue within the lib in how it expects JSON to be available. Revert this change back until that change is investigated and fixed
=> Revert `:github_releases` artifact fetching

lib/mix/tasks/firmware.ex
The defaults disable use of xattrs since those aren't used on any
official or known unofficial Nerves system now, but even if they were,
some additional accommodation for them would be needed to make sure
they're set right given how merging squashfs archives works.
This has a side effect of removing the warnings on MacOS now since the
latest versions of MacOS add an unknown xattr to all files.
This also includes a default of using the quiet option since the
squashfs printout at the end is very verbose and sometimes scrolls good
warnings off the terminal.
=> Add default mksquashfs flags when none specified

mix.exs
Based on discussions with #833 (and for #830)
This will add some consistency to the tooling and reduce the chances for errors during HTTP requests when `:nerves` may be used in a project that has no JSON codec defined.
Specifying a codec is still supported if the user wishes to use a different one.
=> Require `:jason` dependency

mix.exs
This doesn't work and is surprising confusing since the error happens
long after the archive.install step.
=> Prevent accidentally installing nerves as an archive

lib/nerves/artifact/resolvers/github_api.ex, lib/nerves/utils.ex
Since `Jason` is now a required dependency, this removes the ability to specify alternate JSON libraries and emits a warning if is found in the Application config environment
=> Remove :json_codec configuration option 

scripts/nerves_system_compatibility.exs
The compatibility script would download everything to `scripts/tmp` which could cause issues when trying to publish this package since all those files would be included according to the `mix.exs`.
This changes to use `System.tmp_dir!` for the download files and also adds a cleanup step at the end to remove the bulk of the content
=> Move compatibility script downloads to tmp folder 

lib/nerves/artifact.ex, lib/nerves/artifact/resolvers/github_api.ex, test/nerves/artifact/resolvers_github_api_test.exs, test/nerves/artifact_test.exs
Brings back the use of GitHubAPI for public release artifacts.
Also adds fallback to public URL for public release when the API rate limit is reached rather than just failing. If it still fails, the error message won't be as useful. But that is worth it if it succeeds
=> Use GitHubAPI for public release artifacts

docs/User Interfaces.md
Update mix.exs changes to disable `tailwind` and `phoenix_live_reload` on non-host devices
=> Improve phoenix ui setup in `User Interfaces.md`

test/fixtures/integration_app/config/config.exs, test/fixtures/system/mix.exs, test/fixtures/system_artifact/mix.exs, test/fixtures/toolchain/mix.exs, test/nerves/integration_test.exs, test/nerves/release_test.exs, test/support/test_case.ex
Many tests currently rely on `File.cd!/2`, but this [changes the directory globally](https://hexdocs.pm/elixir/File.html#cd!/2) causing race conditions and flaky tests.
This allows us to separate out fixture setup and runs by process by only managing the setup and letting the test process use safe directory changes like with `System.cmd`
This also updates the easier tests to use this new function as a starting point
=> Add `compile_fixture` to `NervesTest.case`

docs/Installation.md
In the prior version it appeared as if fwup instructions were only for arch linux distributions, due to how the headings were arranged.
This addressed [issue 880](https://github.com/nerves-project/nerves/issues/880)
=> Update Installation.md for clarity regarding fwup

lib/nerves/release.ex, test/fixtures/release_app/mix.exs, test/fixtures/release_app/rel/vm.args.eex, test/nerves/release_test.exs
With Elixir 1.15, the way the Elixir IEx shell is started on device has changed and using the old way will break things.
This adds a new check during the release (firmware) initialization and stops the firmware build if the old method is still there
> **Note**
> Using Elixir 1.15 
> ![image](https://github.com/nerves-project/nerves/assets/11321326/31d0fce1-b277-466b-8916-4bc15df9bfb1)
>
> Using Elixir < 1.15
> ![image](https://github.com/nerves-project/nerves/assets/11321326/5aaf331d-27fd-488c-96c6-62ae948bc3f5)
=> Prevent bad vm.args in Nerves firmware

mix.exs
Alternative to #902
The latest dialyxir update only supports Elixir >= 1.12, but Nerves supports 1.11 so CI for that version fails.
This moves the `dialyxir` dep to the `:dev` env since it is not needed during tests and prevents the version check from failing
=> Move `dialyxir` to `:dev` env

lib/nerves/artifact/build_runners/docker.ex, lib/nerves/artifact/build_runners/local.ex
OTP 26 made some big changes around serial interface and it breaks the `mix nerves.system.shell` task. In the end, the main issue is that we no longer have an easy way to take over the STDIN of the task to forward it to a shell running in the system build directory.
Many attempts were made to recapture STDIN, but decided that for now we need to move on. Instead, this adjusts the task to do _all_ the setup for the build directory as before and outputs a warning to the user for the command that can be manually run in order to get the same shell that was previously started with `mix nerves.system.shell`
**Docker error**
**Local (Linux) error**
=> Adjust `mix nerves.system.shell` for OTP 26

docs/User Interfaces.md
Some precisions on the relevant Phoenix configuration - the point isn't to give every possible variation on Phoenix configuration in the Nerves docs, but since the advice given is to copy some of Phoenix's required config in `target.exs`, this can result in confusion on some boards that do not have an easy way to give feedback before they fully boot. 
Maybe this is too much hand-holding ? The idea isn't to merge as-is but first discuss if that kind of "notice" has its place. In my case, I lost a few minutes before realizing that Swoosh defaulted to `hackney` on my board as its transport layer if you did not configure it to use Finch, and hackney isn't included in phoenix dependencies..
=> Update User Interfaces.md

docs/Installation.md
Ubuntu 22.04.3 LTS cannot install package `python`. Install package `python3` instead. Add a section heading instead of continuing the fwup section. Use consistent capitalization for "Nerves system" and "Nerves systems."
=> Update Python version in Installation.md

docs/FAQ.md
A small update to the FAQ clarifying that Nerves Hub is a self-hosted option only.
=> Nerves Hub can only be self-hosted

lib/mix/tasks/compile.nerves_package.ex
Fixes #927
This previously ignored the return of `Nerves.Env.ensure_loaded/1` which could actually return an `{:error, _}` tuple. When calling the `compile.nerves_package` manually, it would crash with a confusing error.
This instead checks the return and raises on error.
It also adjusts the documentation on how/when this task is used
=> Ensure a package is loaded before `compile.nerves_package`

guides/introduction/getting-started.md
The link to Underjord's Nerves Quickstart video wasn't appearing correctly until I removed the URL of the video.jpg file.
=> Fix link to Underjord's video

guides/core/user-interfaces.md
Solves #962 
This PR updates the `user-interfaces.md` guide to use the latest version of Phoenix (1.7), which also uses `bandit` instead of `plug_cowboy` for the HTTP server.
=> Update User Interface Guide to Use Latest Version of Phoenix

lib/nerves/release.ex
```
warning: 32000..1000 has a default step of -1, please write 32000..1000//-1 instead
lib/nerves/release.ex:76: Nerves.Release.write_rootfs_priorities/3
```
=> Fix Elixir 1.17 warning

lib/nerves/release.ex, test/nerves/release_test.exs
This was a copy/paste error. When Elixir 1.16/1.15, we should be checking for the Elixir 1.17 function `start_cli` to be changed instead
=> Fix incorrect exclusion in vm.args.eex when Elixir 1.15/1.16

lib/nerves/artifact/build_runners/docker.ex
=> Fix Docker builds for nerves_system_br v1.28.0 and later

guides/core/connecting-to-a-nerves-target.md
It had to be removed due to compatibility issues on the official
platforms. While it could be re-enabled, if you know how to do this,
you're probably not reading this guide.
=> Remove USB gadget mode serial since not on official platforms

lib/nerves/artifact/build_runners/docker.ex
Fixes #1004
EDIT:
Turns out we [added `TERM=dumb` to the `nerves_system_br` image starting with v1.28](https://github.com/nerves-project/nerves_system_br/commit/db6f9a2a5848ca75f26c9c4a3b2a7bf80e606da1#diff-181ba968e8b37dc7c64319846e544967221e3b5c1ec96bd070456abe37b2ccf2R17) based on CircleCI Docker template recommendations. This is nice to have for CI envs which is the majority of uses for that image, so this adjusts the Nerves tooling to put the `TERM` value of the user in _or_ default to `xterm-256color` if not set
=> Force `TERM` for docker system shell

guides/introduction/installation.md
This moves the Linux distro-specific parts to tabs to reduce the amount
of text the user sees. It installs a little more in the first package
installation line to cover packages the user may need for building
Erlang and fwup as well.
The big change for Debian and Fedora users is to use asdf to install
fwup which should be easier than the current build-from-sourse
instructions.
Here's what it looks like:
=> Refresh Linux install and install fwup via asdf

guides/core/user-interfaces.md
I noticed that the link to the Hello LiveView example is broken. This change fixes that.
=> Fix link to Hello LiveView example

.circleci/config.yml, lib/mix/nerves/preflight.ex, lib/mix/tasks/burn.ex, lib/mix/tasks/firmware.image.ex, lib/mix/tasks/firmware.metadata.ex, lib/mix/tasks/firmware.patch.ex, lib/mix/tasks/firmware.unpack.ex, lib/mix/tasks/nerves.env.ex, lib/mix/tasks/nerves.loadpaths.ex, lib/mix/tasks/nerves.precompile.ex, lib/nerves/artifact/build_runners/docker.ex, lib/nerves/artifact/resolvers/gitea_api.ex, lib/nerves/package.ex, lib/nerves/port.ex, mix.exs, test/nerves/port_test.exs, test/nerves/release_test.exs, test/support/test_case.ex
Most libraries appear to work just fine with Elixir 1.18 and Nerves, so
remove the warning when building.
=> Officially support Elixir 1.18

guides/advanced/advanced-configuration.md, lib/mix/tasks/firmware.ex
Providing the config for :nerves, :firmware and the key `post_processing_script` will now allow `mix firmware` to pass a flag to rel2fw.sh that tells it what script to run when the filesystem is finalized.
This is the hook required to do filesystem signing for dm-verity and any other similar schemes.
Added some info about it to the advanced configuration guide. Ideally expanded to be a signing guide later when that has been more fully built out.
=> Add hook for post-processing filesystem

lib/nerves/package/platform.ex, lib/nerves/system/br.ex, test/fixtures/host_tool/lib/host_tool/platform.ex, test/fixtures/system_platform/lib/system_platform.ex, test/fixtures/toolchain_platform/lib/toolchain_platform.ex, test/fixtures/umbrella/apps/toolchain_platform/lib/toolchain_platform.ex
This only affects `Nerves.Package.Platform` and its users which should
be almost no one since we never ported Nerves outside of Buildroot.
=> Be explicit of behaviours used rather than use macro

lib/nerves/env.ex, lib/nerves/package.ex
This was where Nerves package configuration existed before it was moved
to the mix.exs. This is REALLY old.
=> Remove last references to the old nerves.exs

lib/nerves/package/platform.ex
This is a partial revert of e0e249d1fad11c7b02e4f2f8d15951da9edd0d2b.
=> Add platform using macro back to fix nerves_toolchain_ctng error

lib/mix/tasks/nerves.env.ex, lib/nerves/env.ex, test/nerves/artifact_test.exs, test/nerves/cache_test.exs, test/nerves/env_test.exs, test/support/test_case.ex
It looks like it was more useful when the Nerves package config was kept
in `nerves.exs`. Now it's just returned from the Mix configuration. This
opens up further simplifications since it's no longer important to make
sure that the Agent is loaded. Performance-wise, it doesn't seem like
the cache was used enough for anyone to notice.
=> Simplify Nerves.Env by removing package config caching

guides/introduction/installation.md, lib/mix/tasks/firmware.ex
See https://asdf-vm.com/guide/upgrading-to-v0-16 for details.
=> Upgrade asdf examples to asdf 0.16 syntax

lib/mix/tasks/nerves.loadpaths.ex
With the base tooling setup, running `mix nerves.system.shell` could trigger a full build for systems because will attempt to ensure the Elixir code is compiled. However, the tooling also ties into `mix compile` to ensure the whole system is built also.
The result is a long time to get to a shell when the goal is to run the system shell for the intent of fixing and/or configuring.
This adds a simple check if the task being run is `nerves.system.shell` and skips this precompilation while also using the parts of the tooling needed to get the right build directories and Docker image/settings setup before the shell
=> Prevent `mix nerves.system.shell` from compiling the system
